schema: 1

name:             Quantum Flux
author:           jotato
description:      QuantumFlux adds ways to generate, store, and transport RF power wirelessly along with powered armor and tools.
homePageUrl:      http://minecraft.curseforge.com/projects/quantumflux
documentationUrl: https://github.com/joekaiser/QuantumFlux/wiki
downloadUrl:      http://minecraft.curseforge.com/projects/quantumflux/files
version: 1.3.4
