schema: 1

group: Armor

    item: Chain Boots
        recipe:
            input: Fire
            pattern: 0.0 0.0 ...
            tools: Crafting Table

    item: Chain Chestplate
        recipe:
            input: Fire
            pattern: 0.0 000 000
            tools: Crafting Table

    item: Chain Helmet
        recipe:
            input: Fire
            pattern: 000 0.0 ...
            tools: Crafting Table

    item: Chain Leggings
        recipe:
            input: Fire
            pattern: 000 0.0 0.0
            tools: Crafting Table

    item: Diamond Boots
        recipe:
            input: Diamond
            pattern: 0.0 0.0 ...
            tools: Crafting Table

    item: Diamond Chestplate
        recipe:
            input: Diamond
            pattern: 0.0 000 000
            tools: Crafting Table

    item: Diamond Helmet
        recipe:
            input: Diamond
            pattern: 000 0.0 ...
            tools: Crafting Table

    item: Diamond Horse Armor
        gatherable: yes

    item: Diamond Leggings
        recipe:
            input: Diamond
            pattern: 000 0.0 0.0
            tools: Crafting Table

    item: Gold Horse Armor
        gatherable: yes

    item: Golden Boots
        recipe:
            input: Gold Ingot
            pattern: 0.0 0.0 ...
            tools: Crafting Table

    item: Golden Chestplate
        recipe:
            input: Gold Ingot
            pattern: 0.0 000 000
            tools: Crafting Table

    item: Golden Helmet
        recipe:
            input: Gold Ingot
            pattern: 000 0.0 ...
            tools: Crafting Table

    item: Golden Leggings
        recipe:
            input: Gold Ingot
            pattern: 000 0.0 0.0
            tools: Crafting Table

    item: Iron Boots
        recipe:
            input: Iron Ingot
            pattern: 0.0 0.0 ...
            tools: Crafting Table

    item: Iron Chestplate
        recipe:
            input: Iron Ingot
            pattern: 0.0 000 000
            tools: Crafting Table

    item: Iron Helmet
        recipe:
            input: Iron Ingot
            pattern: 000 0.0 ...
            tools: Crafting Table

    item: Iron Horse Armor
        gatherable: yes

    item: Iron Leggings
        recipe:
            input: Iron Ingot
            pattern: 000 0.0 0.0
            tools: Crafting Table

    item: Leather Boots
        recipe:
            input: Leather
            pattern: 0.0 0.0 ...
            tools: Crafting Table

    item: Leather Cap
        recipe:
            input: Leather
            pattern: 000 0.0 ...
            tools: Crafting Table

    item: Leather Pants
        recipe:
            input: Leather
            pattern: 000 0.0 0.0
            tools: Crafting Table

    item: Leather Tunic
        recipe:
            input: Leather
            pattern: 0.0 000 000
            tools: Crafting Table

group: Blocks (earthen)

    item: Black Stained Clay
        recipe:
            input: Hardened Clay, Ink Sac
            pattern: 000 010 000
            quantity: 8
            tools: Crafting Table

    item: Blue Stained Clay
        recipe:
            input: Hardened Clay, Lapis Lazuli
            pattern: 000 010 000
            quantity: 8
            tools: Crafting Table

    item: Brick
        recipe:
            input: Brick Stairs
            pattern: ... .0. ...
            quantity: 6
            tools: Pulverizer (Basic)
        recipe:
            input: Bricks
            pattern: ... .0. ...
            quantity: 4
            tools: Pulverizer (Basic)
        recipe:
            input: Bricks Slab
            pattern: ... .0. ...
            quantity: 2
            tools: Pulverizer (Basic)
        recipe:
            input: Clay (item)
            pattern: ... .0. ...
            tools: Redstone Furnace (Basic)
        recipe:
            input: Flower Pot
            pattern: ... .0. ...
            quantity: 3
            tools: Pulverizer (Basic)
        recipe:
            input: Clay (item), Furnace Fuel
            pattern: .0. ... .1.
            tools: Furnace

    item: Brick Stairs
        recipe:
            input: Bricks
            pattern: 0.. 00. 000
            quantity: 4
            tools: Crafting Table

    item: Bricks
        recipe:
            input: Brick
            pattern: 00. 00. ...

    item: Bricks Slab
        recipe:
            input: Bricks
            pattern: 000 ... ...
            quantity: 6
            tools: Crafting Table

    item: Brown Stained Clay
        recipe:
            input: Cocoa Beans, Hardened Clay
            pattern: 111 101 111
            quantity: 8
            tools: Crafting Table

    item: Clay (block)
        recipe:
            input: Clay (item)
            pattern: 00. 00. ...

    item: Clay (item)
        gatherable: yes
        recipe:
            extras: Bucket
            input: Dirt, Slag, Water Bucket
            pattern: 20. 11. ...
            quantity: 4

    item: Cyan Stained Clay
        recipe:
            input: Cyan Dye, Hardened Clay
            pattern: 111 101 111
            quantity: 8
            tools: Crafting Table

    item: Dirt
        gatherable: yes

    item: Farmland
        gatherable: yes

    item: Gravel
        gatherable: yes
        recipe:
            input: Netherrack
            pattern: ... .0. ...
            tools: Pulverizer (Basic)
        recipe:
            input: Stone
            pattern: ... .0. ...
            tools: Pulverizer (Basic)

    item: Gray Stained Clay
        recipe:
            input: Gray Dye, Hardened Clay
            pattern: 111 101 111
            quantity: 8
            tools: Crafting Table

    item: Green Stained Clay
        recipe:
            input: Cactus Green, Hardened Clay
            pattern: 111 101 111
            quantity: 8
            tools: Crafting Table

    item: Hardened Clay
        recipe:
            input: Clay (block)
            pattern: ... .0. ...
            tools: Redstone Furnace (Basic)
        recipe:
            input: Clay (block), Furnace Fuel
            pattern: .0. ... .1.
            tools: Furnace

    item: Light Blue Stained Clay
        recipe:
            input: Hardened Clay, Light Blue Dye
            pattern: 000 010 000
            quantity: 8
            tools: Crafting Table

    item: Light Gray Stained Clay
        recipe:
            input: Hardened Clay, Light Gray Dye
            pattern: 000 010 000
            quantity: 8
            tools: Crafting Table

    item: Lime Stained Clay
        recipe:
            input: Hardened Clay, Lime Dye
            pattern: 000 010 000
            quantity: 8
            tools: Crafting Table

    item: Magenta Stained Clay
        recipe:
            input: Hardened Clay, Magenta Dye
            pattern: 000 010 000
            quantity: 8
            tools: Crafting Table

    item: Mycelium
        gatherable: yes

    item: Nether Brick (block)
        gatherable: yes
        recipe:
            input: Nether Brick (item)
            pattern: 00. 00. ...
        recipe:
            input: 4 Netherrack, Soul Sand
            pattern: ... 0.1 ...
            quantity: 2
            tools: Induction Smelter (Basic)

    item: Nether Brick (item)
        recipe:
            input: Nether Brick (block)
            pattern: ... .0. ...
            quantity: 4
            tools: Pulverizer (Basic)
        recipe:
            input: Nether Brick Slab
            pattern: ... .0. ...
            quantity: 2
            tools: Pulverizer (Basic)
        recipe:
            input: Nether Brick Stairs
            pattern: ... .0. ...
            quantity: 6
            tools: Pulverizer (Basic)
        recipe:
            input: Netherrack
            pattern: ... .0. ...
            tools: Redstone Furnace (Basic)
        recipe:
            input: Furnace Fuel, Netherrack
            pattern: .1. ... .0.
            tools: Furnace

    item: Nether Brick Slab
        recipe:
            input: Nether Brick (block)
            pattern: 000 ... ...
            quantity: 6
            tools: Crafting Table

    item: Nether Brick Stairs
        recipe:
            input: Nether Brick (block)
            pattern: 0.. 00. 000
            quantity: 4
            tools: Crafting Table

    item: Orange Stained Clay
        recipe:
            input: Hardened Clay, Orange Dye
            pattern: 000 010 000
            quantity: 8
            tools: Crafting Table

    item: Pink Stained Clay
        recipe:
            input: Hardened Clay, Pink Dye
            pattern: 000 010 000
            quantity: 8
            tools: Crafting Table

    item: Podzol
        gatherable: yes

    item: Purple Stained Clay
        recipe:
            input: Hardened Clay, Purple Dye
            pattern: 000 010 000
            quantity: 8
            tools: Crafting Table

    item: Red Sand
        gatherable: yes

    item: Red Stained Clay
        recipe:
            input: Hardened Clay, Rose Red
            pattern: 000 010 000
            quantity: 8
            tools: Crafting Table

    item: Sand
        gatherable: yes
        recipe:
            input: Black Stained Glass
            pattern: ... .0. ...
            tools: Pulverizer (Basic)
        recipe:
            input: Blue Stained Glass
            pattern: ... .0. ...
            tools: Pulverizer (Basic)
        recipe:
            input: Brown Stained Glass
            pattern: ... .0. ...
            tools: Pulverizer (Basic)
        recipe:
            input: Chiseled Sandstone
            pattern: ... .0. ...
            quantity: 2
            tools: Pulverizer (Basic)
        recipe:
            input: Cobblestone
            pattern: ... .0. ...
            tools: Pulverizer (Basic)
        recipe:
            input: Cyan Stained Glass
            pattern: ... .0. ...
            tools: Pulverizer (Basic)
        recipe:
            input: Glass
            pattern: ... .0. ...
            tools: Pulverizer (Basic)
        recipe:
            input: Glass Bottle
            pattern: ... .0. ...
            tools: Pulverizer (Basic)
        recipe:
            input: Gray Stained Glass
            pattern: ... .0. ...
            tools: Pulverizer (Basic)
        recipe:
            input: Green Stained Glass
            pattern: ... .0. ...
            tools: Pulverizer (Basic)
        recipe:
            input: Light Blue Stained Glass
            pattern: ... .0. ...
            tools: Pulverizer (Basic)
        recipe:
            input: Light Gray Stained Glass
            pattern: ... .0. ...
            tools: Pulverizer (Basic)
        recipe:
            input: Lime Stained Glass
            pattern: ... .0. ...
            tools: Pulverizer (Basic)
        recipe:
            input: Magenta Stained Glass
            pattern: ... .0. ...
            tools: Pulverizer (Basic)
        recipe:
            input: Orange Stained Glass
            pattern: ... .0. ...
            tools: Pulverizer (Basic)
        recipe:
            input: Pink Stained Glass
            pattern: ... .0. ...
            tools: Pulverizer (Basic)
        recipe:
            input: Purple Stained Glass
            pattern: ... .0. ...
            tools: Pulverizer (Basic)
        recipe:
            input: Red Stained Glass
            pattern: ... .0. ...
            tools: Pulverizer (Basic)
        recipe:
            input: Sandstone
            pattern: ... .0. ...
            quantity: 2
            tools: Pulverizer (Basic)
        recipe:
            input: Sandstone Slab
            pattern: ... .0. ...
            tools: Pulverizer (Basic)
        recipe:
            input: Sandstone Stairs
            pattern: ... .0. ...
            quantity: 2
            tools: Pulverizer (Basic)
        recipe:
            input: Smooth Sandstone
            pattern: ... .0. ...
            quantity: 2
            tools: Pulverizer (Basic)
        recipe:
            input: White Stained Glass
            pattern: ... .0. ...
            tools: Pulverizer (Basic)
        recipe:
            input: Yellow Stained Glass
            pattern: ... .0. ...
            tools: Pulverizer (Basic)

    item: Sandstone
        recipe:
            input: Sand
            pattern: 00. 00. ...

    item: Sandstone Slab
        recipe:
            input: Sandstone
            pattern: 000 ... ...
            quantity: 6
            tools: Crafting Table

    item: Sandstone Stairs
        recipe:
            input: Sandstone
            pattern: 0.. 00. 000
            quantity: 4
            tools: Crafting Table

    item: Smooth Sandstone
        recipe:
            input: Sandstone
            pattern: 00. 00. ...
            quantity: 4

    item: Soul Sand
        gatherable: yes

    item: White Stained Clay
        recipe:
            input: Bone Meal, Hardened Clay
            pattern: 111 101 111
            quantity: 8
            tools: Crafting Table

    item: Yellow Stained Clay
        recipe:
            input: Dandelion Yellow, Hardened Clay
            pattern: 111 101 111
            quantity: 8
            tools: Crafting Table

group: Blocks (glass)

    item: Black Stained Glass
        recipe:
            input: Glass, Ink Sac
            pattern: 000 010 000
            quantity: 8
            tools: Crafting Table

    item: Black Stained Glass Pane
        recipe:
            input: Black Stained Glass
            pattern: 000 000 ...
            quantity: 16
            tools: Crafting Table

    item: Blue Stained Glass
        recipe:
            input: Glass, Lapis Lazuli
            pattern: 000 010 000
            quantity: 8
            tools: Crafting Table

    item: Blue Stained Glass Pane
        recipe:
            input: Blue Stained Glass
            pattern: 000 000 ...
            quantity: 16
            tools: Crafting Table

    item: Brown Stained Glass
        recipe:
            input: Cocoa Beans, Glass
            pattern: 111 101 111
            quantity: 8
            tools: Crafting Table

    item: Brown Stained Glass Pane
        recipe:
            input: Brown Stained Glass
            pattern: 000 000 ...
            quantity: 16
            tools: Crafting Table

    item: Cyan Stained Glass
        recipe:
            input: Cyan Dye, Glass
            pattern: 111 101 111
            quantity: 8
            tools: Crafting Table

    item: Cyan Stained Glass Pane
        recipe:
            input: Cyan Stained Glass
            pattern: 000 000 ...
            quantity: 16
            tools: Crafting Table

    item: Glass
        recipe:
            input: Sand
            pattern: ... .0. ...
            tools: Redstone Furnace (Basic)
        recipe:
            input: Furnace Fuel, Sand
            pattern: .1. ... .0.
            tools: Furnace

    item: Glass Pane
        recipe:
            input: Glass
            pattern: 000 000 ...
            quantity: 16
            tools: Crafting Table

    item: Gray Stained Glass
        recipe:
            input: Glass, Gray Dye
            pattern: 000 010 000
            quantity: 8
            tools: Crafting Table

    item: Gray Stained Glass Pane
        recipe:
            input: Gray Stained Glass
            pattern: 000 000 ...
            quantity: 16
            tools: Crafting Table

    item: Green Stained Glass
        recipe:
            input: Cactus Green, Glass
            pattern: 111 101 111
            quantity: 8
            tools: Crafting Table

    item: Green Stained Glass Pane
        recipe:
            input: Green Stained Glass
            pattern: 000 000 ...
            quantity: 16
            tools: Crafting Table

    item: Light Blue Stained Glass
        recipe:
            input: Glass, Light Blue Dye
            pattern: 000 010 000
            quantity: 8
            tools: Crafting Table

    item: Light Blue Stained Glass Pane
        recipe:
            input: Light Blue Stained Glass
            pattern: 000 000 ...
            quantity: 16
            tools: Crafting Table

    item: Light Gray Stained Glass
        recipe:
            input: Glass, Light Gray Dye
            pattern: 000 010 000
            quantity: 8
            tools: Crafting Table

    item: Light Gray Stained Glass Pane
        recipe:
            input: Light Gray Stained Glass
            pattern: 000 000 ...
            quantity: 16
            tools: Crafting Table

    item: Lime Stained Glass
        recipe:
            input: Glass, Lime Dye
            pattern: 000 010 000
            quantity: 8
            tools: Crafting Table

    item: Lime Stained Glass Pane
        recipe:
            input: Lime Stained Glass
            pattern: 000 000 ...
            quantity: 16
            tools: Crafting Table

    item: Magenta Stained Glass
        recipe:
            input: Glass, Magenta Dye
            pattern: 000 010 000
            quantity: 8
            tools: Crafting Table

    item: Magenta Stained Glass Pane
        recipe:
            input: Magenta Stained Glass
            pattern: 000 000 ...
            quantity: 16
            tools: Crafting Table

    item: Orange Stained Glass
        recipe:
            input: Glass, Orange Dye
            pattern: 000 010 000
            quantity: 8
            tools: Crafting Table

    item: Orange Stained Glass Pane
        recipe:
            input: Orange Stained Glass
            pattern: 000 000 ...
            quantity: 16
            tools: Crafting Table

    item: Pink Stained Glass
        recipe:
            input: Glass, Pink Dye
            pattern: 000 010 000
            quantity: 8
            tools: Crafting Table

    item: Pink Stained Glass Pane
        recipe:
            input: Pink Stained Glass
            pattern: 000 000 ...
            quantity: 16
            tools: Crafting Table

    item: Purple Stained Glass
        recipe:
            input: Glass, Purple Dye
            pattern: 000 010 000
            quantity: 8
            tools: Crafting Table

    item: Purple Stained Glass Pane
        recipe:
            input: Purple Stained Glass
            pattern: 000 000 ...
            quantity: 16
            tools: Crafting Table

    item: Red Stained Glass
        recipe:
            input: Glass, Rose Red
            pattern: 000 010 000
            quantity: 8
            tools: Crafting Table

    item: Red Stained Glass Pane
        recipe:
            input: Red Stained Glass
            pattern: 000 000 ...
            quantity: 16
            tools: Crafting Table

    item: White Stained Glass
        recipe:
            input: Bone Meal, Glass
            pattern: 111 101 111
            quantity: 8
            tools: Crafting Table

    item: White Stained Glass Pane
        recipe:
            input: White Stained Glass
            pattern: 000 000 ...
            quantity: 16
            tools: Crafting Table

    item: Yellow Stained Glass
        recipe:
            input: Dandelion Yellow, Glass
            pattern: 111 101 111
            quantity: 8
            tools: Crafting Table

    item: Yellow Stained Glass Pane
        recipe:
            input: Yellow Stained Glass
            pattern: 000 000 ...
            quantity: 16
            tools: Crafting Table

group: Blocks (stone)

    item: Bedrock
        gatherable: yes

    item: Chiseled Sandstone
        recipe:
            input: Sandstone Slab
            pattern: 0.. 0.. ...

    item: Chiseled Stone Bricks
        gatherable: yes

    item: Cobblestone
        gatherable: yes
        recipe:
            input: Lever
            pattern: ... .0. ...
            tools: Sawmill (Basic)
        recipe:
            extras: 1000 Lava, 1000 Water
            input: 1000 Lava, 1000 Water
            pattern: ... 1.0 ...
            tools: Igneous Extruder (Basic)

    item: Cobblestone Slab
        recipe:
            input: Cobblestone
            pattern: 000 ... ...
            quantity: 6
            tools: Crafting Table

    item: Cobblestone Wall
        recipe:
            input: Cobblestone
            pattern: 000 000 ...
            quantity: 6
            tools: Crafting Table

    item: Cracked Stone Bricks
        recipe:
            input: Stone Bricks
            pattern: ... .0. ...
            tools: Pulverizer (Basic)

    item: End Stone
        recipe:
            input: 250 Resonant Ender, Sandstone
            pattern: ... 1.0 ...
            tools: Fluid Transposer (Basic)

    item: Moss Stone
        recipe:
            input: Cobblestone, 250 Water
            pattern: ... 0.1 ...
            tools: Fluid Transposer (Basic)

    item: Mossy Cobblestone Wall
        recipe:
            input: Moss Stone
            pattern: 000 000 ...
            quantity: 6
            tools: Crafting Table

    item: Mossy Stone Bricks
        recipe:
            input: Stone Bricks, 250 Water
            pattern: ... 0.1 ...
            tools: Fluid Transposer (Basic)

    item: Netherrack
        gatherable: yes

    item: Obsidian
        gatherable: yes
        recipe:
            input: 1000 Lava, 1000 Water
            pattern: ... 1.0 ...
            tools: Igneous Extruder (Basic)

    item: Quartz Slab
        recipe:
            input: Block of Quartz
            pattern: 000 ... ...
            quantity: 6
            tools: Crafting Table

    item: Quartz Stairs
        recipe:
            input: Block of Quartz
            pattern: 0.. 00. 000
            quantity: 4
            tools: Crafting Table

    item: Stone
        recipe:
            input: Cobblestone
            pattern: ... .0. ...
            tools: Redstone Furnace (Basic)
        recipe:
            input: Cobblestone, Furnace Fuel
            pattern: .0. ... .1.
            tools: Furnace
        recipe:
            extras: 1000 Lava
            input: 1000 Lava, 1000 Water
            pattern: ... 1.0 ...
            tools: Igneous Extruder (Basic)

    item: Stone Brick Stairs
        recipe:
            input: Stone Bricks
            pattern: 0.. 00. 000
            quantity: 4
            tools: Crafting Table

    item: Stone Bricks
        recipe:
            input: Stone
            pattern: 00. 00. ...
            quantity: 4
        recipe:
            input: 2 Cobblestone, Sand
            pattern: ... 0.1 ...
            tools: Induction Smelter (Basic)

    item: Stone Bricks Slab
        recipe:
            input: Stone Bricks
            pattern: 000 ... ...
            quantity: 6
            tools: Crafting Table

    item: Stone Slab
        recipe:
            input: Stone
            pattern: 000 ... ...
            quantity: 6
            tools: Crafting Table

    item: Stone Stairs
        recipe:
            input: Cobblestone
            pattern: 0.. 00. 000
            quantity: 4
            tools: Crafting Table

group: Blocks (tools)

    item: Anvil
        recipe:
            input: Block of Iron, Iron Ingot
            pattern: 000 .1. 111
            tools: Crafting Table

    item: Beacon
        recipe:
            input: Glass, Nether Star, Obsidian
            pattern: 000 010 222
            tools: Crafting Table

    item: Bed
        recipe:
            input: Oak Wood Planks, Wool
            pattern: 111 000 ...
            tools: Crafting Table

    item: Cauldron
        recipe:
            input: Iron Ingot
            pattern: 0.0 0.0 000
            tools: Crafting Table

    item: Chest
        recipe:
            input: Oak Wood Planks
            pattern: 000 0.0 000
            tools: Crafting Table

    item: Command Block
        gatherable: yes

    item: Crafting Table
        recipe:
            input: Oak Wood Planks
            pattern: 00. 00. ...

    item: Ender Chest
        recipe:
            input: Eye of Ender, Obsidian
            pattern: 111 101 111
            tools: Crafting Table

    item: Furnace
        recipe:
            input: Cobblestone
            pattern: 000 0.0 000
            tools: Crafting Table

    item: Jukebox
        recipe:
            input: Diamond, Oak Wood Planks
            pattern: 111 101 111
            tools: Crafting Table

    item: Trapped Chest
        recipe:
            input: Chest, Tripwire Hook
            pattern: 01. ... ...

group: Blocks (wooden)

    item: Acacia Wood Planks
        recipe:
            input: Acacia Wood
            pattern: 0.. ... ...
            quantity: 4
        recipe:
            input: Acacia Wood
            pattern: ... .0. ...
            quantity: 6
            tools: Sawmill (Basic)
        recipe:
            input: 2 Acacia Wood Stairs
            pattern: ... .0. ...
            quantity: 3
            tools: Sawmill (Basic)

    item: Acacia Wood Slab
        recipe:
            input: Acacia Wood Planks
            pattern: 000 ... ...
            quantity: 6
            tools: Crafting Table

    item: Acacia Wood Stairs
        recipe:
            input: Acacia Wood Planks
            pattern: 0.. 00. 000
            quantity: 4
            tools: Crafting Table

    item: Birch Wood Planks
        recipe:
            input: Birch Wood
            pattern: 0.. ... ...
            quantity: 4
        recipe:
            input: Birch Wood
            pattern: ... .0. ...
            quantity: 6
            tools: Sawmill (Basic)
        recipe:
            input: 2 Birch Wood Stairs
            pattern: ... .0. ...
            quantity: 3
            tools: Sawmill (Basic)

    item: Birch Wood Slab
        recipe:
            input: Birch Wood Planks
            pattern: 000 ... ...
            quantity: 6
            tools: Crafting Table

    item: Birch Wood Stairs
        recipe:
            input: Birch Wood Planks
            pattern: 0.. 00. 000
            quantity: 4
            tools: Crafting Table

    item: Dark Oak Wood Planks
        recipe:
            input: Dark Oak Wood
            pattern: 0.. ... ...
            quantity: 4
        recipe:
            input: Dark Oak Wood
            pattern: ... .0. ...
            quantity: 6
            tools: Sawmill (Basic)
        recipe:
            input: 2 Dark Oak Wood Stairs
            pattern: ... .0. ...
            quantity: 3
            tools: Sawmill (Basic)

    item: Dark Oak Wood Slab
        recipe:
            input: Dark Oak Wood Planks
            pattern: 000 ... ...
            quantity: 6
            tools: Crafting Table

    item: Dark Oak Wood Stairs
        recipe:
            input: Dark Oak Wood Planks
            pattern: 0.. 00. 000
            quantity: 4
            tools: Crafting Table

    item: Fence
        recipe:
            input: Stick
            pattern: 000 000 ...
            quantity: 2
            tools: Crafting Table

    item: Fence Gate
        recipe:
            input: Oak Wood Planks, Stick
            pattern: 101 101 ...
            tools: Crafting Table

    item: Jungle Wood Planks
        recipe:
            input: Jungle Wood
            pattern: 0.. ... ...
            quantity: 4
        recipe:
            input: Jungle Wood
            pattern: ... .0. ...
            quantity: 6
            tools: Sawmill (Basic)
        recipe:
            input: 2 Jungle Wood Stairs
            pattern: ... .0. ...
            quantity: 3
            tools: Sawmill (Basic)

    item: Jungle Wood Slab
        recipe:
            input: Jungle Wood Planks
            pattern: 000 ... ...
            quantity: 6
            tools: Crafting Table

    item: Jungle Wood Stairs
        recipe:
            input: Jungle Wood Planks
            pattern: 0.. 00. 000
            quantity: 4
            tools: Crafting Table

    item: Nether Brick Fence
        recipe:
            input: Nether Brick (block)
            pattern: 000 000 ...
            quantity: 6
            tools: Crafting Table

    item: Oak Wood Planks
        recipe:
            input: Oak Wood
            pattern: 0.. ... ...
            quantity: 4
        recipe:
            input: Bed
            pattern: ... .0. ...
            quantity: 3
            tools: Sawmill (Basic)
        recipe:
            input: Boat
            pattern: ... .0. ...
            quantity: 5
            tools: Sawmill (Basic)
        recipe:
            input: Bookshelf
            pattern: ... .0. ...
            quantity: 6
            tools: Sawmill (Basic)
        recipe:
            input: Button (wooden)
            pattern: ... .0. ...
            tools: Sawmill (Basic)
        recipe:
            input: Chest
            pattern: ... .0. ...
            quantity: 8
            tools: Sawmill (Basic)
        recipe:
            input: Crafting Table
            pattern: ... .0. ...
            quantity: 4
            tools: Sawmill (Basic)
        recipe:
            input: Fence Gate
            pattern: ... .0. ...
            quantity: 2
            tools: Sawmill (Basic)
        recipe:
            input: Jukebox
            pattern: ... .0. ...
            quantity: 8
            tools: Sawmill (Basic)
        recipe:
            input: Note Block
            pattern: ... .0. ...
            quantity: 8
            tools: Sawmill (Basic)
        recipe:
            input: Oak Wood
            pattern: ... .0. ...
            quantity: 6
            tools: Sawmill (Basic)
        recipe:
            input: Pressure Plate (wooden)
            pattern: ... .0. ...
            quantity: 2
            tools: Sawmill (Basic)
        recipe:
            input: Sign
            pattern: ... .0. ...
            quantity: 2
            tools: Sawmill (Basic)
        recipe:
            input: Trapdoor
            pattern: ... .0. ...
            quantity: 3
            tools: Sawmill (Basic)
        recipe:
            input: Wooden Axe
            pattern: ... .0. ...
            quantity: 2
            tools: Sawmill (Basic)
        recipe:
            input: Wooden Door
            pattern: ... .0. ...
            quantity: 6
            tools: Sawmill (Basic)
        recipe:
            input: Wooden Hoe
            pattern: ... .0. ...
            tools: Sawmill (Basic)
        recipe:
            input: Wooden Pickaxe
            pattern: ... .0. ...
            quantity: 2
            tools: Sawmill (Basic)
        recipe:
            input: Wooden Shovel
            pattern: ... .0. ...
            tools: Sawmill (Basic)
        recipe:
            input: Wooden Sword
            pattern: ... .0. ...
            tools: Sawmill (Basic)
        recipe:
            input: 2 Bowl
            pattern: ... .0. ...
            tools: Sawmill (Basic)
        recipe:
            input: 2 Oak Wood Stairs
            pattern: ... .0. ...
            quantity: 3
            tools: Sawmill (Basic)

    item: Oak Wood Slab
        recipe:
            input: Oak Wood Planks
            pattern: 000 ... ...
            quantity: 6
            tools: Crafting Table

    item: Oak Wood Stairs
        recipe:
            input: Oak Wood Planks
            pattern: 0.. 00. 000
            quantity: 4
            tools: Crafting Table

    item: Spruce Wood Planks
        recipe:
            input: Spruce Wood
            pattern: 0.. ... ...
            quantity: 4
        recipe:
            input: Spruce Wood
            pattern: ... .0. ...
            quantity: 6
            tools: Sawmill (Basic)
        recipe:
            input: 2 Spruce Wood Stairs
            pattern: ... .0. ...
            quantity: 3
            tools: Sawmill (Basic)

    item: Spruce Wood Slab
        recipe:
            input: Spruce Wood Planks
            pattern: 000 ... ...
            quantity: 6
            tools: Crafting Table

    item: Spruce Wood Stairs
        recipe:
            input: Spruce Wood Planks
            pattern: 0.. 00. 000
            quantity: 4
            tools: Crafting Table

group: Brewing (potions)

    item: Potion of Fire Resistance (3:00)
        recipe:
            input: Awkward Potion, Magma Cream
            pattern: .1. ... 000
            quantity: 3
            tools: Brewing Stand

    item: Potion of Fire Resistance (8:00)
        recipe:
            input: Potion of Fire Resistance (3:00), Redstone
            pattern: .1. ... 000
            quantity: 3
            tools: Brewing Stand

    item: Potion of Instant Damage
        recipe:
            input: Fermented Spider Eye, Potion of Instant Health
            pattern: .0. ... 111
            quantity: 3
            tools: Brewing Stand
        recipe:
            input: Fermented Spider Eye, Potion of Poison (0:45)
            pattern: .0. ... 111
            quantity: 3
            tools: Brewing Stand
        recipe:
            input: Fermented Spider Eye, Potion of Water Breathing (3:00)
            pattern: .0. ... 111
            quantity: 3
            tools: Brewing Stand

    item: Potion of Instant Damage II
        recipe:
            input: Fermented Spider Eye, Potion of Instant Health II
            pattern: .0. ... 111
            quantity: 3
            tools: Brewing Stand
        recipe:
            input: Fermented Spider Eye, Potion of Poison II (0:22)
            pattern: .0. ... 111
            quantity: 3
            tools: Brewing Stand
        recipe:
            input: Glowstone Dust, Potion of Instant Damage
            pattern: .0. ... 111
            quantity: 3
            tools: Brewing Stand

    item: Potion of Instant Health
        recipe:
            input: Awkward Potion, Glistering Melon
            pattern: .1. ... 000
            quantity: 3
            tools: Brewing Stand

    item: Potion of Instant Health II
        recipe:
            input: Glowstone Dust, Potion of Instant Health
            pattern: .0. ... 111
            quantity: 3
            tools: Brewing Stand

    item: Potion of Invisibility (3:00)
        recipe:
            input: Fermented Spider Eye, Potion of Night Vision (3:00)
            pattern: .0. ... 111
            quantity: 3
            tools: Brewing Stand

    item: Potion of Invisibility (8:00)
        recipe:
            input: Fermented Spider Eye, Potion of Night Vision (8:00)
            pattern: .0. ... 111
            quantity: 3
            tools: Brewing Stand
        recipe:
            input: Potion of Invisibility (3:00), Redstone
            pattern: .1. ... 000
            quantity: 3
            tools: Brewing Stand

    item: Potion of Night Vision (3:00)
        recipe:
            input: Awkward Potion, Golden Carrot
            pattern: .1. ... 000
            quantity: 3
            tools: Brewing Stand

    item: Potion of Night Vision (8:00)
        recipe:
            input: Potion of Night Vision (3:00), Redstone
            pattern: .1. ... 000
            quantity: 3
            tools: Brewing Stand

    item: Potion of Poison (0:45)
        recipe:
            input: Awkward Potion, Spider Eye
            pattern: .1. ... 000
            quantity: 3
            tools: Brewing Stand

    item: Potion of Poison (2:00)
        recipe:
            input: Potion of Poison (0:45), Redstone
            pattern: .1. ... 000
            quantity: 3
            tools: Brewing Stand

    item: Potion of Poison II (0:22)
        recipe:
            input: Glowstone Dust, Potion of Poison (0:45)
            pattern: .0. ... 111
            quantity: 3
            tools: Brewing Stand
        recipe:
            input: Glowstone Dust, Potion of Poison (2:00)
            pattern: .0. ... 111
            quantity: 3
            tools: Brewing Stand

    item: Potion of Regeneration (0:45)
        recipe:
            input: Awkward Potion, Ghast Tear
            pattern: .1. ... 000
            quantity: 3
            tools: Brewing Stand

    item: Potion of Regeneration (2:00)
        recipe:
            input: Potion of Regeneration (0:45), Redstone
            pattern: .1. ... 000
            quantity: 3
            tools: Brewing Stand
        recipe:
            input: Potion of Regeneration II (0:22), Redstone
            pattern: .1. ... 000
            quantity: 3
            tools: Brewing Stand

    item: Potion of Regeneration II (0:22)
        recipe:
            input: Glowstone Dust, Potion of Regeneration (0:45)
            pattern: .0. ... 111
            quantity: 3
            tools: Brewing Stand

    item: Potion of Slowness (1:30)
        recipe:
            input: Fermented Spider Eye, Potion of Fire Resistance (3:00)
            pattern: .0. ... 111
            quantity: 3
            tools: Brewing Stand
        recipe:
            input: Fermented Spider Eye, Potion of Speed (3:00)
            pattern: .0. ... 111
            quantity: 3
            tools: Brewing Stand

    item: Potion of Slowness (4:00)
        recipe:
            input: Fermented Spider Eye, Potion of Fire Resistance (8:00)
            pattern: .0. ... 111
            quantity: 3
            tools: Brewing Stand
        recipe:
            input: Fermented Spider Eye, Potion of Speed (8:00)
            pattern: .0. ... 111
            quantity: 3
            tools: Brewing Stand
        recipe:
            input: Potion of Slowness (1:30), Redstone
            pattern: .1. ... 000
            quantity: 3
            tools: Brewing Stand

    item: Potion of Speed (3:00)
        recipe:
            input: Awkward Potion, Sugar
            pattern: .1. ... 000
            quantity: 3
            tools: Brewing Stand

    item: Potion of Speed (8:00)
        recipe:
            input: Potion of Speed (3:00), Redstone
            pattern: .1. ... 000
            quantity: 3
            tools: Brewing Stand

    item: Potion of Speed II (1:30)
        recipe:
            input: Glowstone Dust, Potion of Speed (3:00)
            pattern: .0. ... 111
            quantity: 3
            tools: Brewing Stand
        recipe:
            input: Glowstone Dust, Potion of Speed (8:00)
            pattern: .0. ... 111
            quantity: 3
            tools: Brewing Stand

    item: Potion of Strength (3:00)
        recipe:
            input: Awkward Potion, Blaze Powder
            pattern: .1. ... 000
            quantity: 3
            tools: Brewing Stand

    item: Potion of Strength (8:00)
        recipe:
            input: Potion of Strength (3:00), Redstone
            pattern: .1. ... 000
            quantity: 3
            tools: Brewing Stand
        recipe:
            input: Potion of Strength II (1:30), Redstone
            pattern: .1. ... 000
            quantity: 3
            tools: Brewing Stand

    item: Potion of Strength II (1:30)
        recipe:
            input: Glowstone Dust, Potion of Strength (3:00)
            pattern: .0. ... 111
            quantity: 3
            tools: Brewing Stand

    item: Potion of Water Breathing (3:00)
        recipe:
            input: Awkward Potion, Pufferfish
            pattern: .1. ... 000
            quantity: 3
            tools: Brewing Stand

    item: Potion of Water Breathing (8:00)
        recipe:
            input: Potion of Water Breathing (3:00), Redstone
            pattern: .1. ... 000
            quantity: 3
            tools: Brewing Stand

    item: Potion of Weakness (1:30)
        recipe:
            input: Fermented Spider Eye, Water Bottle
            pattern: .0. ... 111
            quantity: 3
            tools: Brewing Stand

    item: Potion of Weakness (4:00)
        recipe:
            input: Potion of Weakness (1:30), Redstone
            pattern: .1. ... 000
            quantity: 3
            tools: Brewing Stand

    item: Splash Potion of Fire Resistance (2:15)
        recipe:
            input: Gunpowder, Potion of Fire Resistance (3:00)
            pattern: .0. ... 111
            quantity: 3
            tools: Brewing Stand

    item: Splash Potion of Fire Resistance (6:00)
        recipe:
            input: Gunpowder, Potion of Fire Resistance (8:00)
            pattern: .0. ... 111
            quantity: 3
            tools: Brewing Stand
        recipe:
            input: Redstone, Splash Potion of Fire Resistance (2:15)
            pattern: .0. ... 111
            quantity: 3
            tools: Brewing Stand

    item: Splash Potion of Instant Damage
        recipe:
            input: Fermented Spider Eye, Splash Potion of Instant Health
            pattern: .0. ... 111
            quantity: 3
            tools: Brewing Stand
        recipe:
            input: Fermented Spider Eye, Splash Potion of Poison (0:33)
            pattern: .0. ... 111
            quantity: 3
            tools: Brewing Stand
        recipe:
            input: Fermented Spider Eye, Splash Potion of Water Breathing (2:15)
            pattern: .0. ... 111
            quantity: 3
            tools: Brewing Stand
        recipe:
            input: Gunpowder, Potion of Instant Damage
            pattern: .0. ... 111
            quantity: 3
            tools: Brewing Stand

    item: Splash Potion of Instant Damage II
        recipe:
            input: Fermented Spider Eye, Splash Potion of Instant Health II
            pattern: .0. ... 111
            quantity: 3
            tools: Brewing Stand
        recipe:
            input: Fermented Spider Eye, Splash Potion of Poison II (0:16)
            pattern: .0. ... 111
            quantity: 3
            tools: Brewing Stand
        recipe:
            input: Glowstone Dust, Splash Potion of Instant Damage
            pattern: .0. ... 111
            quantity: 3
            tools: Brewing Stand
        recipe:
            input: Gunpowder, Potion of Instant Damage II
            pattern: .0. ... 111
            quantity: 3
            tools: Brewing Stand

    item: Splash Potion of Instant Health
        recipe:
            input: Gunpowder, Potion of Instant Health
            pattern: .0. ... 111
            quantity: 3
            tools: Brewing Stand

    item: Splash Potion of Instant Health II
        recipe:
            input: Glowstone Dust, Splash Potion of Instant Health
            pattern: .0. ... 111
            quantity: 3
            tools: Brewing Stand
        recipe:
            input: Gunpowder, Potion of Instant Health II
            pattern: .0. ... 111
            quantity: 3
            tools: Brewing Stand

    item: Splash Potion of Invisibility (2:15)
        recipe:
            input: Fermented Spider Eye, Splash Potion of Night Vision (2:15)
            pattern: .0. ... 111
            quantity: 3
            tools: Brewing Stand
        recipe:
            input: Gunpowder, Potion of Invisibility (3:00)
            pattern: .0. ... 111
            quantity: 3
            tools: Brewing Stand

    item: Splash Potion of Invisibility (6:00)
        recipe:
            input: Fermented Spider Eye, Splash Potion of Night Vision (6:00)
            pattern: .0. ... 111
            quantity: 3
            tools: Brewing Stand
        recipe:
            input: Gunpowder, Potion of Invisibility (8:00)
            pattern: .0. ... 111
            quantity: 3
            tools: Brewing Stand
        recipe:
            input: Redstone, Splash Potion of Invisibility (2:15)
            pattern: .0. ... 111
            quantity: 3
            tools: Brewing Stand

    item: Splash Potion of Night Vision (2:15)
        recipe:
            input: Gunpowder, Potion of Night Vision (3:00)
            pattern: .0. ... 111
            quantity: 3
            tools: Brewing Stand

    item: Splash Potion of Night Vision (6:00)
        recipe:
            input: Gunpowder, Potion of Night Vision (8:00)
            pattern: .0. ... 111
            quantity: 3
            tools: Brewing Stand
        recipe:
            input: Redstone, Splash Potion of Night Vision (2:15)
            pattern: .0. ... 111
            quantity: 3
            tools: Brewing Stand

    item: Splash Potion of Poison (0:33)
        recipe:
            input: Gunpowder, Potion of Poison (0:45)
            pattern: .0. ... 111
            quantity: 3
            tools: Brewing Stand

    item: Splash Potion of Poison (1:30)
        recipe:
            input: Gunpowder, Potion of Poison (2:00)
            pattern: .0. ... 111
            quantity: 3
            tools: Brewing Stand
        recipe:
            input: Redstone, Splash Potion of Poison (0:33)
            pattern: .0. ... 111
            quantity: 3
            tools: Brewing Stand

    item: Splash Potion of Poison II (0:16)
        recipe:
            input: Glowstone Dust, Splash Potion of Poison (0:33)
            pattern: .0. ... 111
            quantity: 3
            tools: Brewing Stand
        recipe:
            input: Glowstone Dust, Splash Potion of Poison (1:30)
            pattern: .0. ... 111
            quantity: 3
            tools: Brewing Stand
        recipe:
            input: Gunpowder, Potion of Poison II (0:22)
            pattern: .0. ... 111
            quantity: 3
            tools: Brewing Stand

    item: Splash Potion of Regeneration (0:33)
        recipe:
            input: Gunpowder, Potion of Regeneration (0:45)
            pattern: .0. ... 111
            quantity: 3
            tools: Brewing Stand

    item: Splash Potion of Regeneration (1:30)
        recipe:
            input: Gunpowder, Potion of Regeneration (2:00)
            pattern: .0. ... 111
            quantity: 3
            tools: Brewing Stand
        recipe:
            input: Redstone, Splash Potion of Regeneration (0:33)
            pattern: .0. ... 111
            quantity: 3
            tools: Brewing Stand

    item: Splash Potion of Regeneration II (0:16)
        recipe:
            input: Glowstone Dust, Splash Potion of Regeneration (0:33)
            pattern: .0. ... 111
            quantity: 3
            tools: Brewing Stand
        recipe:
            input: Glowstone Dust, Splash Potion of Regeneration (1:30)
            pattern: .0. ... 111
            quantity: 3
            tools: Brewing Stand
        recipe:
            input: Gunpowder, Potion of Regeneration II (0:22)
            pattern: .0. ... 111
            quantity: 3
            tools: Brewing Stand

    item: Splash Potion of Slowness (1:07)
        recipe:
            input: Fermented Spider Eye, Splash Potion of Fire Resistance (2:15)
            pattern: .0. ... 111
            quantity: 3
            tools: Brewing Stand
        recipe:
            input: Fermented Spider Eye, Splash Potion of Speed (2:15)
            pattern: .0. ... 111
            quantity: 3
            tools: Brewing Stand
        recipe:
            input: Gunpowder, Potion of Slowness (1:30)
            pattern: .0. ... 111
            quantity: 3
            tools: Brewing Stand

    item: Splash Potion of Slowness (3:00)
        recipe:
            input: Fermented Spider Eye, Splash Potion of Fire Resistance (6:00)
            pattern: .0. ... 111
            quantity: 3
            tools: Brewing Stand
        recipe:
            input: Fermented Spider Eye, Splash Potion of Speed (6:00)
            pattern: .0. ... 111
            quantity: 3
            tools: Brewing Stand
        recipe:
            input: Gunpowder, Potion of Slowness (4:00)
            pattern: .0. ... 111
            quantity: 3
            tools: Brewing Stand
        recipe:
            input: Redstone, Splash Potion of Slowness (1:07)
            pattern: .0. ... 111
            quantity: 3
            tools: Brewing Stand

    item: Splash Potion of Speed (2:15)
        recipe:
            input: Gunpowder, Potion of Speed (3:00)
            pattern: .0. ... 111
            quantity: 3
            tools: Brewing Stand

    item: Splash Potion of Speed (6:00)
        recipe:
            input: Gunpowder, Potion of Speed (8:00)
            pattern: .0. ... 111
            quantity: 3
            tools: Brewing Stand
        recipe:
            input: Redstone, Splash Potion of Speed (2:15)
            pattern: .0. ... 111
            quantity: 3
            tools: Brewing Stand
        recipe:
            input: Redstone, Splash Potion of Speed II (1:07)
            pattern: .0. ... 111
            quantity: 3
            tools: Brewing Stand

    item: Splash Potion of Speed II (1:07)
        recipe:
            input: Glowstone Dust, Splash Potion of Speed (2:15)
            pattern: .0. ... 111
            quantity: 3
            tools: Brewing Stand
        recipe:
            input: Gunpowder, Potion of Speed II (1:30)
            pattern: .0. ... 111
            quantity: 3
            tools: Brewing Stand

    item: Splash Potion of Strength (2:15)
        recipe:
            input: Gunpowder, Potion of Strength (3:00)
            pattern: .0. ... 111
            quantity: 3
            tools: Brewing Stand

    item: Splash Potion of Strength (6:00)
        recipe:
            input: Gunpowder, Potion of Strength (8:00)
            pattern: .0. ... 111
            quantity: 3
            tools: Brewing Stand
        recipe:
            input: Redstone, Splash Potion of Strength (2:15)
            pattern: .0. ... 111
            quantity: 3
            tools: Brewing Stand
        recipe:
            input: Redstone, Splash Potion of Strength II (1:07)
            pattern: .0. ... 111
            quantity: 3
            tools: Brewing Stand

    item: Splash Potion of Strength II (1:07)
        recipe:
            input: Glowstone Dust, Splash Potion of Strength (2:15)
            pattern: .0. ... 111
            quantity: 3
            tools: Brewing Stand
        recipe:
            input: Gunpowder, Potion of Strength II (1:30)
            pattern: .0. ... 111
            quantity: 3
            tools: Brewing Stand

    item: Splash Potion of Water Breathing (2:15)
        recipe:
            input: Gunpowder, Potion of Water Breathing (3:00)
            pattern: .0. ... 111
            quantity: 3
            tools: Brewing Stand

    item: Splash Potion of Water Breathing (6:00)
        recipe:
            input: Gunpowder, Potion of Water Breathing (8:00)
            pattern: .0. ... 111
            quantity: 3
            tools: Brewing Stand
        recipe:
            input: Redstone, Splash Potion of Water Breathing (2:15)
            pattern: .0. ... 111
            quantity: 3
            tools: Brewing Stand

    item: Splash Potion of Weakness (1:07)
        recipe:
            input: Gunpowder, Potion of Weakness (1:30)
            pattern: .0. ... 111
            quantity: 3
            tools: Brewing Stand

    item: Splash Potion of Weakness (3:00)
        recipe:
            input: Gunpowder, Potion of Weakness (4:00)
            pattern: .0. ... 111
            quantity: 3
            tools: Brewing Stand
        recipe:
            input: Redstone, Splash Potion of Weakness (1:07)
            pattern: .0. ... 111
            quantity: 3
            tools: Brewing Stand

group: Brewing (supplies)

    item: Awkward Potion
        recipe:
            input: Nether Wart, Water Bottle
            pattern: .0. ... 111
            quantity: 3
            tools: Brewing Stand

    item: Brewing Stand
        recipe:
            input: Blaze Rod, Cobblestone
            pattern: .0. 111 ...
            tools: Crafting Table

    item: Fermented Spider Eye
        recipe:
            input: Mushroom (brown), Spider Eye, Sugar
            pattern: .2. 01. ...

    item: Ghast Tear
        gatherable: yes

    item: Glistering Melon
        recipe:
            input: Gold Nugget, Melon (item)
            pattern: 000 010 000
            tools: Crafting Table

    item: Golden Carrot
        recipe:
            input: Carrot, Gold Nugget
            pattern: 111 101 111
            tools: Crafting Table

    item: Gunpowder
        recipe:
            input: Niter, Pulverized Charcoal, Sulfur
            pattern: 12. 00. ...
            quantity: 2
        recipe:
            input: Niter, Pulverized Coal, Sulfur
            pattern: 12. 00. ...
            quantity: 2

    item: Magma Cream
        gatherable: yes
        recipe:
            input: Blaze Powder, Slimeball
            pattern: ... 10. ...

    item: Mundane Potion
        recipe:
            input: Blaze Powder, Water Bottle
            pattern: .0. ... 111
            quantity: 3
            tools: Brewing Stand
        recipe:
            input: Ghast Tear, Water Bottle
            pattern: .0. ... 111
            quantity: 3
            tools: Brewing Stand
        recipe:
            input: Glistering Melon, Water Bottle
            pattern: .0. ... 111
            quantity: 3
            tools: Brewing Stand
        recipe:
            input: Magma Cream, Water Bottle
            pattern: .0. ... 111
            quantity: 3
            tools: Brewing Stand
        recipe:
            input: Redstone, Water Bottle
            pattern: .0. ... 111
            quantity: 3
            tools: Brewing Stand
        recipe:
            input: Spider Eye, Water Bottle
            pattern: .0. ... 111
            quantity: 3
            tools: Brewing Stand
        recipe:
            input: Sugar, Water Bottle
            pattern: .0. ... 111
            quantity: 3
            tools: Brewing Stand

    item: Nether Wart
        gatherable: yes

    item: Potent Potion
        recipe:
            input: Awkward Potion, Glowstone Dust
            pattern: .1. ... 000
            quantity: 3
            tools: Brewing Stand

    item: Thick Potion
        recipe:
            input: Glowstone Dust, Water Bottle
            pattern: .0. ... 111
            quantity: 3
            tools: Brewing Stand

group: Carpets

    item: Black Carpet
        recipe:
            input: Black Wool
            pattern: 00. ... ...
            quantity: 3

    item: Blue Carpet
        recipe:
            input: Blue Wool
            pattern: 00. ... ...
            quantity: 3

    item: Brown Carpet
        recipe:
            input: Brown Wool
            pattern: 00. ... ...
            quantity: 3

    item: Carpet
        recipe:
            input: Wool
            pattern: 00. ... ...
            quantity: 3

    item: Cyan Carpet
        recipe:
            input: Cyan Wool
            pattern: 00. ... ...
            quantity: 3

    item: Gray Carpet
        recipe:
            input: Gray Wool
            pattern: 00. ... ...
            quantity: 3

    item: Green Carpet
        recipe:
            input: Green Wool
            pattern: 00. ... ...
            quantity: 3

    item: Light Blue Carpet
        recipe:
            input: Light Blue Wool
            pattern: 00. ... ...
            quantity: 3

    item: Light Gray Carpet
        recipe:
            input: Light Gray Wool
            pattern: 00. ... ...
            quantity: 3

    item: Lime Carpet
        recipe:
            input: Lime Wool
            pattern: 00. ... ...
            quantity: 3

    item: Magenta Carpet
        recipe:
            input: Magenta Wool
            pattern: 00. ... ...
            quantity: 3

    item: Orange Carpet
        recipe:
            input: Orange Wool
            pattern: 00. ... ...
            quantity: 3

    item: Pink Carpet
        recipe:
            input: Pink Wool
            pattern: 00. ... ...
            quantity: 3

    item: Purple Carpet
        recipe:
            input: Purple Wool
            pattern: 00. ... ...
            quantity: 3

    item: Red Carpet
        recipe:
            input: Red Wool
            pattern: 00. ... ...
            quantity: 3

    item: Yellow Carpet
        recipe:
            input: Yellow Wool
            pattern: 00. ... ...
            quantity: 3

group: Decorative

    item: Cobweb
        gatherable: yes

    item: End Portal
        gatherable: yes

    item: Fire
        gatherable: yes

    item: Iron Bars
        recipe:
            input: Iron Ingot
            pattern: 000 000 ...
            quantity: 16
            tools: Crafting Table

    item: Jack o'Lantern
        recipe:
            input: Pumpkin, Torch
            pattern: 0.. 1.. ...

    item: Monster Spawner
        gatherable: yes

    item: Sign
        recipe:
            input: Oak Wood Planks, Stick
            pattern: 000 000 .1.
            quantity: 3
            tools: Crafting Table

    item: Sponge
        gatherable: yes

group: Dyes

    item: Bone Meal
        recipe:
            input: Bone
            pattern: ... .0. ...
            quantity: 3
        recipe:
            input: Bone
            pattern: ... .0. ...
            quantity: 6
            tools: Pulverizer (Basic)

    item: Cactus Green
        recipe:
            input: Cactus
            pattern: ... .0. ...
            tools: Redstone Furnace (Basic)
        recipe:
            input: Cactus, Furnace Fuel
            pattern: .0. ... .1.
            tools: Furnace
        recipe:
            input: Cactus Seeds, Phyto-Gro
            pattern: ... 0.1 ...
            tools: Phytogenic Insolator (Basic)
        recipe:
            input: Cactus Seeds, Rich Phyto-Gro
            pattern: ... 0.1 ...
            quantity: 3
            tools: Phytogenic Insolator (Basic)

    item: Cocoa Beans
        gatherable: yes
        recipe:
            input: Cocoa Beans, Phyto-Gro
            pattern: ... 0.1 ...
            quantity: 3
            tools: Phytogenic Insolator (Basic)
        recipe:
            input: Cocoa Beans, Rich Phyto-Gro
            pattern: ... 0.1 ...
            quantity: 9
            tools: Phytogenic Insolator (Basic)

    item: Cyan Dye
        recipe:
            input: Cactus Green, Lapis Lazuli
            pattern: ... 01. ...
            quantity: 2

    item: Dandelion Yellow
        recipe:
            input: Dandelion
            pattern: ... .0. ...
        recipe:
            input: Sunflower
            pattern: ... .0. ...
            quantity: 2
        recipe:
            input: Dandelion
            pattern: ... .0. ...
            quantity: 4
            tools: Pulverizer (Basic)
        recipe:
            input: Sunflower
            pattern: ... .0. ...
            quantity: 8
            tools: Pulverizer (Basic)
        recipe:
            input: Dandelion Seeds, Phyto-Gro
            pattern: ... 0.1 ...
            tools: Phytogenic Insolator (Basic)
        recipe:
            input: Dandelion Seeds, Rich Phyto-Gro
            pattern: ... 0.1 ...
            quantity: 3
            tools: Phytogenic Insolator (Basic)

    item: Gray Dye
        recipe:
            input: Bone Meal, Ink Sac
            pattern: ... 01. ...
            quantity: 2

    item: Ink Sac
        gatherable: yes

    item: Lapis Lazuli
        gatherable: yes
        recipe:
            input: Lapis Lazuli Block
            pattern: 0.. ... ...
            quantity: 9
        recipe:
            input: Lapis Lazuli Ore
            pattern: ... .0. ...
            quantity: 12
            tools: Pulverizer (Basic)
        recipe:
            input: Lapis Lazuli Ore
            pattern: ... .0. ...
            quantity: 6
            tools: Redstone Furnace (Basic)
        recipe:
            input: Furnace Fuel, Lapis Lazuli Ore
            pattern: .1. ... .0.
            tools: Furnace
        recipe:
            input: Lapender Seeds, Phyto-Gro
            pattern: ... 0.1 ...
            tools: Phytogenic Insolator (Basic)
        recipe:
            input: Lapender Seeds, Rich Phyto-Gro
            pattern: ... 0.1 ...
            quantity: 3
            tools: Phytogenic Insolator (Basic)

    item: Light Blue Dye
        recipe:
            input: Blue Orchid
            pattern: ... .0. ...
        recipe:
            input: Bone Meal, Lapis Lazuli
            pattern: ... 01. ...
            quantity: 2
        recipe:
            input: Blue Orchid
            pattern: ... .0. ...
            quantity: 4
            tools: Pulverizer (Basic)
        recipe:
            input: Blue Orchid Seeds, Phyto-Gro
            pattern: ... 0.1 ...
            tools: Phytogenic Insolator (Basic)
        recipe:
            input: Blue Orchid Seeds, Rich Phyto-Gro
            pattern: ... 0.1 ...
            quantity: 3
            tools: Phytogenic Insolator (Basic)

    item: Light Gray Dye
        recipe:
            input: Azure Bluet
            pattern: ... .0. ...
        recipe:
            input: Oxeye Daisy
            pattern: ... .0. ...
        recipe:
            input: White Tulip
            pattern: ... .0. ...
        recipe:
            input: Bone Meal, Gray Dye
            pattern: ... 01. ...
            quantity: 2
        recipe:
            input: Bone Meal, Ink Sac
            pattern: .0. 01. ...
            quantity: 3
        recipe:
            input: Azure Bluet
            pattern: ... .0. ...
            quantity: 4
            tools: Pulverizer (Basic)
        recipe:
            input: Oxeye Daisy
            pattern: ... .0. ...
            quantity: 4
            tools: Pulverizer (Basic)
        recipe:
            input: White Tulip
            pattern: ... .0. ...
            quantity: 4
            tools: Pulverizer (Basic)
        recipe:
            input: Daisy Seeds, Phyto-Gro
            pattern: ... 0.1 ...
            tools: Phytogenic Insolator (Basic)
        recipe:
            input: Daisy Seeds, Rich Phyto-Gro
            pattern: ... 0.1 ...
            quantity: 3
            tools: Phytogenic Insolator (Basic)
        recipe:
            input: Phyto-Gro, White Tulip Seeds
            pattern: ... 1.0 ...
            tools: Phytogenic Insolator (Basic)
        recipe:
            input: Rich Phyto-Gro, White Tulip Seeds
            pattern: ... 1.0 ...
            quantity: 3
            tools: Phytogenic Insolator (Basic)

    item: Lime Dye
        recipe:
            input: Bone Meal, Cactus Green
            pattern: ... 01. ...
            quantity: 2

    item: Magenta Dye
        recipe:
            input: Allium
            pattern: ... .0. ...
        recipe:
            input: Lilac
            pattern: ... .0. ...
            quantity: 2
        recipe:
            input: Pink Dye, Purple Dye
            pattern: ... 01. ...
            quantity: 2
        recipe:
            input: Lapis Lazuli, Pink Dye, Rose Red
            pattern: .1. 20. ...
            quantity: 3
        recipe:
            input: Bone Meal, Lapis Lazuli, Rose Red
            pattern: 02. 21. ...
            quantity: 4
        recipe:
            input: Allium
            pattern: ... .0. ...
            quantity: 4
            tools: Pulverizer (Basic)
        recipe:
            input: Lilac
            pattern: ... .0. ...
            quantity: 8
            tools: Pulverizer (Basic)
        recipe:
            input: Allium Seeds, Phyto-Gro
            pattern: ... 0.1 ...
            tools: Phytogenic Insolator (Basic)
        recipe:
            input: Allium Seeds, Rich Phyto-Gro
            pattern: ... 0.1 ...
            quantity: 3
            tools: Phytogenic Insolator (Basic)

    item: Orange Dye
        recipe:
            input: Orange Tulip
            pattern: ... .0. ...
        recipe:
            input: Dandelion Yellow, Rose Red
            pattern: ... 01. ...
            quantity: 2
        recipe:
            input: Orange Tulip
            pattern: ... .0. ...
            quantity: 4
            tools: Pulverizer (Basic)
        recipe:
            input: Orange Tulip Seeds, Phyto-Gro
            pattern: ... 0.1 ...
            tools: Phytogenic Insolator (Basic)
        recipe:
            input: Orange Tulip Seeds, Rich Phyto-Gro
            pattern: ... 0.1 ...
            quantity: 3
            tools: Phytogenic Insolator (Basic)

    item: Pink Dye
        recipe:
            input: Peony
            pattern: ... .0. ...
            quantity: 2
        recipe:
            input: Pink Tulip
            pattern: ... .0. ...
        recipe:
            input: Bone Meal, Rose Red
            pattern: ... 01. ...
            quantity: 2
        recipe:
            input: Peony
            pattern: ... .0. ...
            quantity: 8
            tools: Pulverizer (Basic)
        recipe:
            input: Pink Tulip
            pattern: ... .0. ...
            quantity: 4
            tools: Pulverizer (Basic)
        recipe:
            input: Phyto-Gro, Pink Tulip Seeds
            pattern: ... 1.0 ...
            tools: Phytogenic Insolator (Basic)
        recipe:
            input: Pink Tulip Seeds, Rich Phyto-Gro
            pattern: ... 0.1 ...
            quantity: 3
            tools: Phytogenic Insolator (Basic)

    item: Purple Dye
        recipe:
            input: Lapis Lazuli, Rose Red
            pattern: ... 10. ...
            quantity: 2

    item: Rose Red
        recipe:
            input: Poppy
            pattern: ... .0. ...
        recipe:
            input: Red Tulip
            pattern: ... .0. ...
        recipe:
            input: Rose Bush
            pattern: ... .0. ...
            quantity: 2
        recipe:
            input: Poppy
            pattern: ... .0. ...
            quantity: 4
            tools: Pulverizer (Basic)
        recipe:
            input: Red Tulip
            pattern: ... .0. ...
            quantity: 4
            tools: Pulverizer (Basic)
        recipe:
            input: Rose Bush
            pattern: ... .0. ...
            quantity: 8
            tools: Pulverizer (Basic)
        recipe:
            input: Phyto-Gro, Poppy Seeds
            pattern: ... 1.0 ...
            tools: Phytogenic Insolator (Basic)
        recipe:
            input: Phyto-Gro, Red Tulip Seeds
            pattern: ... 1.0 ...
            tools: Phytogenic Insolator (Basic)
        recipe:
            input: Poppy Seeds, Rich Phyto-Gro
            pattern: ... 0.1 ...
            quantity: 3
            tools: Phytogenic Insolator (Basic)
        recipe:
            input: Red Tulip Seeds, Rich Phyto-Gro
            pattern: ... 0.1 ...
            quantity: 3
            tools: Phytogenic Insolator (Basic)

group: Enchanting

    item: Enchanted Book
        gatherable: yes

    item: Enchantment Table
        recipe:
            input: Book, Diamond, Obsidian
            pattern: .0. 121 222
            tools: Crafting Table

group: Fireworks

    item: Fire Charge
        recipe:
            input: Blaze Powder, Charcoal, Gunpowder
            pattern: .1. 02. ...
            quantity: 3
        recipe:
            input: Blaze Powder, Coal, Gunpowder
            pattern: .1. 02. ...
            quantity: 3

    item: Firework Rocket
        gatherable: yes

    item: Firework Star
        gatherable: yes

group: Flowers

    item: Allium
        gatherable: yes

    item: Azure Bluet
        gatherable: yes

    item: Blue Orchid
        gatherable: yes

    item: Dandelion
        gatherable: yes

    item: Lilac
        gatherable: yes

    item: Orange Tulip
        gatherable: yes

    item: Oxeye Daisy
        gatherable: yes

    item: Peony
        gatherable: yes

    item: Pink Tulip
        gatherable: yes

    item: Poppy
        gatherable: yes

    item: Red Tulip
        gatherable: yes

    item: Rose Bush
        gatherable: yes

    item: Sunflower
        gatherable: yes

    item: White Tulip
        gatherable: yes

group: Food

    item: Apple
        gatherable: yes

    item: Baked Potato
        recipe:
            input: Potato
            pattern: ... .0. ...
            tools: Redstone Furnace (Basic)
        recipe:
            input: Furnace Fuel, Potato
            pattern: .1. ... .0.
            tools: Furnace

    item: Bread
        recipe:
            input: Wheat
            pattern: 000 ... ...
            tools: Crafting Table

    item: Cake
        recipe:
            extras: 3 Bucket
            input: Egg, Milk, Sugar, Wheat
            pattern: 111 202 333
            tools: Crafting Table

    item: Carrot
        gatherable: yes
        recipe:
            input: Carrot, Phyto-Gro
            pattern: ... 0.1 ...
            quantity: 3
            tools: Phytogenic Insolator (Basic)
        recipe:
            input: Carrot, Rich Phyto-Gro
            pattern: ... 0.1 ...
            quantity: 9
            tools: Phytogenic Insolator (Basic)
        recipe:
            input: Carrot Seeds, Phyto-Gro
            pattern: ... 0.1 ...
            tools: Phytogenic Insolator (Basic)
        recipe:
            input: Carrot Seeds, Rich Phyto-Gro
            pattern: ... 0.1 ...
            quantity: 3
            tools: Phytogenic Insolator (Basic)

    item: Clownfish
        gatherable: yes

    item: Cooked Chicken
        recipe:
            input: Raw Chicken
            pattern: ... .0. ...
            tools: Redstone Furnace (Basic)
        recipe:
            input: Furnace Fuel, Raw Chicken
            pattern: .1. ... .0.
            tools: Furnace

    item: Cooked Fish
        recipe:
            input: Raw Fish
            pattern: ... .0. ...
            tools: Redstone Furnace (Basic)
        recipe:
            input: Furnace Fuel, Raw Fish
            pattern: .1. ... .0.
            tools: Furnace

    item: Cooked Porkchop
        recipe:
            input: Raw Porkchop
            pattern: ... .0. ...
            tools: Redstone Furnace (Basic)
        recipe:
            input: Furnace Fuel, Raw Porkchop
            pattern: .1. ... .0.
            tools: Furnace

    item: Cooked Salmon
        recipe:
            input: Raw Salmon
            pattern: ... .0. ...
            tools: Redstone Furnace (Basic)
        recipe:
            input: Furnace Fuel, Raw Salmon
            pattern: .1. ... .0.
            tools: Furnace

    item: Cookie
        recipe:
            input: Cocoa Beans, Wheat
            pattern: 101 ... ...
            quantity: 8
            tools: Crafting Table

    item: Golden Apple
        recipe:
            input: Apple, Gold Ingot
            pattern: 111 101 111
            tools: Crafting Table

    item: Golden Apple (magical)
        recipe:
            input: Apple, Block of Gold
            pattern: 111 101 111
            tools: Crafting Table

    item: Hay Bale
        recipe:
            input: Wheat
            pattern: 000 000 000
            tools: Crafting Table

    item: Melon (item)
        gatherable: yes
        recipe:
            input: Melon (block)
            pattern: ... .0. ...
            quantity: 9
            tools: Sawmill (Basic)

    item: Melon (block)
        recipe:
            input: Melon Seeds, Phyto-Gro
            pattern: ... 0.1 ...
            tools: Phytogenic Insolator (Basic)
        recipe:
            input: Melon Seeds, Rich Phyto-Gro
            pattern: ... 0.1 ...
            quantity: 3
            tools: Phytogenic Insolator (Basic)
        recipe:
            input: Melon (item)
            pattern: 000 000 000
            tools: Crafting Table

    item: Melon Seeds
        recipe:
            input: Melon (item)
            pattern: 0.. ... ...
        recipe:
            extras: Carrot Seeds, Crop Sticks, Dirt, Pumpkin Seeds
            input: Carrot Seeds, 2 Crop Sticks, Dirt, Pumpkin Seeds
            pattern: 013 .2. ...
            tools: Crafting Table

    item: Milk
        gatherable: yes

    item: Mushroom (brown)
        gatherable: yes
        recipe:
            input: Brown Mushroom Spores, Phyto-Gro
            pattern: ... 0.1 ...
            tools: Phytogenic Insolator (Basic)
        recipe:
            input: Brown Mushroom Spores, Rich Phyto-Gro
            pattern: ... 0.1 ...
            quantity: 3
            tools: Phytogenic Insolator (Basic)

    item: Mushroom (red)
        gatherable: yes
        recipe:
            input: Phyto-Gro, Red Mushroom Spores
            pattern: ... 1.0 ...
            tools: Phytogenic Insolator (Basic)
        recipe:
            input: Red Mushroom Spores, Rich Phyto-Gro
            pattern: ... 0.1 ...
            quantity: 3
            tools: Phytogenic Insolator (Basic)

    item: Mushroom Stew
        recipe:
            input: Bowl, Mushroom (brown), Mushroom (red)
            pattern: .0. 21. ...

    item: Poisonous Potato
        gatherable: yes

    item: Potato
        gatherable: yes
        recipe:
            input: Phyto-Gro, Potato
            pattern: ... 1.0 ...
            quantity: 3
            tools: Phytogenic Insolator (Basic)
        recipe:
            input: Phyto-Gro, Potato Seeds
            pattern: ... 1.0 ...
            tools: Phytogenic Insolator (Basic)
        recipe:
            input: Potato, Rich Phyto-Gro
            pattern: ... 0.1 ...
            quantity: 9
            tools: Phytogenic Insolator (Basic)
        recipe:
            input: Potato Seeds, Rich Phyto-Gro
            pattern: ... 0.1 ...
            quantity: 3
            tools: Phytogenic Insolator (Basic)

    item: Pufferfish
        gatherable: yes

    item: Pumpkin
        gatherable: yes
        recipe:
            input: Phyto-Gro, Pumpkin Seeds
            pattern: ... 1.0 ...
            tools: Phytogenic Insolator (Basic)
        recipe:
            input: Pumpkin Seeds, Rich Phyto-Gro
            pattern: ... 0.1 ...
            quantity: 3
            tools: Phytogenic Insolator (Basic)

    item: Pumpkin Pie
        recipe:
            input: Egg, Pumpkin, Sugar
            pattern: .0. 21. ...

    item: Pumpkin Seeds
        recipe:
            input: Pumpkin
            pattern: 0.. ... ...
            quantity: 4
        recipe:
            extras: Carrot Seeds, Crop Sticks, Dirt, Potato Seeds
            input: Carrot Seeds, 2 Crop Sticks, Dirt, Potato Seeds
            pattern: 310 .2. ...
            tools: Crafting Table

    item: Raw Beef
        gatherable: yes

    item: Raw Chicken
        gatherable: yes

    item: Raw Fish
        gatherable: yes

    item: Raw Porkchop
        gatherable: yes

    item: Raw Salmon
        gatherable: yes

    item: Seeds
        recipe:
            input: Wheat
            pattern: ... .0. ...

    item: Steak
        recipe:
            input: Raw Beef
            pattern: ... .0. ...
            tools: Redstone Furnace (Basic)
        recipe:
            input: Furnace Fuel, Raw Beef
            pattern: .1. ... .0.
            tools: Furnace

    item: Sugar
        recipe:
            input: Sugar Canes
            pattern: 0.. ... ...
        recipe:
            input: Sugar Canes
            pattern: ... .0. ...
            quantity: 2
            tools: Pulverizer (Basic)

    item: Sugar Canes
        recipe:
            input: Phyto-Gro, Sugar Canes
            pattern: ... 1.0 ...
            quantity: 2
            tools: Phytogenic Insolator (Basic)
        recipe:
            input: Phyto-Gro, Sugarcane Seeds
            pattern: ... 1.0 ...
            tools: Phytogenic Insolator (Basic)
        recipe:
            input: Rich Phyto-Gro, Sugar Canes
            pattern: ... 1.0 ...
            quantity: 6
            tools: Phytogenic Insolator (Basic)
        recipe:
            input: Rich Phyto-Gro, Sugarcane Seeds
            pattern: ... 1.0 ...
            quantity: 3
            tools: Phytogenic Insolator (Basic)

    item: Wheat
        gatherable: yes
        recipe:
            input: Hay Bale
            pattern: 0.. ... ...
            quantity: 9
        recipe:
            input: Phyto-Gro, Seeds
            pattern: ... 1.0 ...
            tools: Phytogenic Insolator (Basic)
        recipe:
            input: Rich Phyto-Gro, Seeds
            pattern: ... 1.0 ...
            quantity: 3
            tools: Phytogenic Insolator (Basic)

group: Household Items

    item: Book
        recipe:
            input: Leather, Paper
            pattern: 01. 11. ...

    item: Book and Quill
        recipe:
            input: Book, Feather, Ink Sac
            pattern: .1. 20. ...

    item: Bookshelf
        recipe:
            input: Book, Oak Wood Planks
            pattern: 111 000 111
            tools: Crafting Table

    item: Bottle o' Enchanting
        gatherable: yes

    item: Bowl
        recipe:
            input: Oak Wood Slab
            pattern: 0.0 .0. ...
            quantity: 4
            tools: Crafting Table

    item: Flower Pot
        recipe:
            input: Brick
            pattern: 0.0 .0. ...
            tools: Crafting Table

    item: Glass Bottle
        recipe:
            extras: 1000 Water
            input: Water Bottle
            pattern: ... .0. ...
            tools: Fluid Transposer (Basic)
        recipe:
            input: Glass
            pattern: 0.0 .0. ...
            quantity: 3
            tools: Crafting Table

    item: Iron Door
        recipe:
            input: Iron Ingot
            pattern: 00. 00. 00.
            tools: Crafting Table

    item: Item Frame
        recipe:
            input: Leather, Stick
            pattern: 111 101 111
            tools: Crafting Table

    item: Ladder
        recipe:
            input: Stick
            pattern: 0.0 000 0.0
            quantity: 3
            tools: Crafting Table

    item: Music Disc (11)
        gatherable: yes

    item: Music Disc (13)
        gatherable: yes

    item: Music Disc (blocks)
        gatherable: yes

    item: Music Disc (cat)
        gatherable: yes

    item: Music Disc (chirp)
        gatherable: yes

    item: Music Disc (far)
        gatherable: yes

    item: Music Disc (mall)
        gatherable: yes

    item: Music Disc (mellohi)
        gatherable: yes

    item: Music Disc (stal)
        gatherable: yes

    item: Music Disc (strad)
        gatherable: yes

    item: Music Disc (wait)
        gatherable: yes

    item: Music Disc (ward)
        gatherable: yes

    item: Painting
        recipe:
            input: Stick, Wool
            pattern: 000 010 000
            tools: Crafting Table

    item: Paper
        recipe:
            input: Sugar Canes
            pattern: 000 ... ...
            quantity: 3
            tools: Crafting Table
        recipe:
            extras: Bucket
            input: Sawdust, Water Bucket
            pattern: .0. 010 .0.
            quantity: 2
            tools: Crafting Table

    item: Water Bottle
        recipe:
            input: Glass Bottle, 1000 Water
            pattern: ... 0.1 ...
            tools: Fluid Transposer (Basic)

    item: Wooden Door
        recipe:
            input: Oak Wood Planks
            pattern: 00. 00. 00.
            tools: Crafting Table

    item: Written Book
        gatherable: yes

group: Liquids

    item: Bucket
        recipe:
            extras: 1000 Blazing Pyrotheum
            input: Blazing Pyrotheum Bucket
            pattern: ... .0. ...
            tools: Fluid Transposer (Basic)
        recipe:
            extras: 1000 Destabilized Redstone
            input: Destabilized Redstone Bucket
            pattern: ... .0. ...
            tools: Fluid Transposer (Basic)
        recipe:
            extras: 1000 Energized Glowstone
            input: Energized Glowstone Bucket
            pattern: ... .0. ...
            tools: Fluid Transposer (Basic)
        recipe:
            extras: 1000 Fuel
            input: Fuel Bucket
            pattern: ... .0. ...
            tools: Fluid Transposer (Basic)
        recipe:
            extras: 1000 Gelid Cryotheum
            input: Gelid Cryotheum Bucket
            pattern: ... .0. ...
            tools: Fluid Transposer (Basic)
        recipe:
            extras: 1000 Lava
            input: Lava Bucket
            pattern: ... .0. ...
            tools: Fluid Transposer (Basic)
        recipe:
            extras: 1000 Liquifacted Coal
            input: Liquifacted Coal Bucket
            pattern: ... .0. ...
            tools: Fluid Transposer (Basic)
        recipe:
            extras: 1000 Oil
            input: Oil Bucket
            pattern: ... .0. ...
            tools: Fluid Transposer (Basic)
        recipe:
            extras: 1000 Primal Mana
            input: Primal Mana Bucket
            pattern: ... .0. ...
            tools: Fluid Transposer (Basic)
        recipe:
            extras: 1000 Resonant Ender
            input: Resonant Ender Bucket
            pattern: ... .0. ...
            tools: Fluid Transposer (Basic)
        recipe:
            extras: 1000 Tectonic Petrotheum
            input: Tectonic Petrotheum Bucket
            pattern: ... .0. ...
            tools: Fluid Transposer (Basic)
        recipe:
            extras: 1000 Water
            input: Water Bucket
            pattern: ... .0. ...
            tools: Fluid Transposer (Basic)
        recipe:
            extras: 1000 Zephyrean Aerotheum
            input: Zephyrean Aerotheum Bucket
            pattern: ... .0. ...
            tools: Fluid Transposer (Basic)
        recipe:
            input: Iron Ingot
            pattern: 0.0 .0. ...
            tools: Crafting Table

    item: Lava
        gatherable: yes
        recipe:
            input: Blaze Rod
            pattern: ... .0. ...
            quantity: 250
            tools: Magma Crucible (Basic)
        recipe:
            input: Cobblestone
            pattern: ... .0. ...
            quantity: 1000
            tools: Magma Crucible (Basic)
        recipe:
            input: Netherrack
            pattern: ... .0. ...
            quantity: 1000
            tools: Magma Crucible (Basic)
        recipe:
            input: Obsidian
            pattern: ... .0. ...
            quantity: 1000
            tools: Magma Crucible (Basic)
        recipe:
            input: Stone
            pattern: ... .0. ...
            quantity: 1000
            tools: Magma Crucible (Basic)

    item: Lava Bucket
        recipe:
            input: Bucket, 1000 Lava
            pattern: ... 0.1 ...
            tools: Fluid Transposer (Basic)

    item: Water
        gatherable: yes
        recipe:
            input: Ice
            pattern: ... .0. ...
            quantity: 1000
            tools: Magma Crucible (Basic)
        recipe:
            input: Snow (block)
            pattern: ... .0. ...
            quantity: 500
            tools: Magma Crucible (Basic)
        recipe:
            input: Snowball
            pattern: ... .0. ...
            quantity: 125
            tools: Magma Crucible (Basic)

    item: Water Bucket
        recipe:
            input: Bucket, 1000 Water
            pattern: ... 0.1 ...
            tools: Fluid Transposer (Basic)

group: Machines

    item: Button (stone)
        recipe:
            input: Stone
            pattern: 0.. ... ...

    item: Button (wooden)
        recipe:
            input: Oak Wood Planks
            pattern: 0.. ... ...

    item: Daylight Sensor
        recipe:
            input: Glass, Nether Quartz, Oak Wood Slab
            pattern: 000 111 222
            tools: Crafting Table

    item: Dispenser
        recipe:
            input: Bow, Cobblestone, Redstone
            pattern: 111 101 121
            tools: Crafting Table

    item: Dropper
        recipe:
            input: Cobblestone, Redstone
            pattern: 000 0.0 010
            tools: Crafting Table

    item: Hopper
        recipe:
            input: Chest, Iron Ingot
            pattern: 1.1 101 .1.
            tools: Crafting Table

    item: Lever
        recipe:
            input: Cobblestone, Stick
            pattern: 1.. 0.. ...

    item: Piston
        recipe:
            input: Cobblestone, Iron Ingot, Oak Wood Planks, Redstone
            pattern: 222 010 030
            tools: Crafting Table

    item: Pressure Plate (stone)
        recipe:
            input: Stone
            pattern: 00. ... ...

    item: Pressure Plate (wooden)
        recipe:
            input: Oak Wood Planks
            pattern: 00. ... ...

    item: Redstone Comparator
        recipe:
            input: Nether Quartz, Redstone Torch, Stone
            pattern: .1. 101 222
            tools: Crafting Table

    item: Redstone Lamp
        recipe:
            input: Glowstone, Redstone
            pattern: .1. 101 .1.
            tools: Crafting Table

    item: Redstone Repeater
        recipe:
            input: Redstone, Redstone Torch, Stone
            pattern: 101 222 ...
            tools: Crafting Table

    item: Redstone Torch
        recipe:
            input: Redstone, Stick
            pattern: 0.. 1.. ...

    item: Sticky Piston
        recipe:
            input: Piston, Slimeball
            pattern: 1.. 0.. ...

    item: Trapdoor
        recipe:
            input: Oak Wood Planks
            pattern: 000 000 ...
            quantity: 2
            tools: Crafting Table

    item: Tripwire Hook
        recipe:
            input: Iron Ingot, Oak Wood Planks, Stick
            pattern: 0.. 2.. 1..
            quantity: 2
            tools: Crafting Table

    item: Weighted Pressure Plate (Heavy)
        recipe:
            input: Iron Ingot
            pattern: 00. ... ...

    item: Weighted Pressure Plate (Light)
        recipe:
            input: Gold Ingot
            pattern: 00. ... ...

group: Minerals

    item: Block of Coal
        recipe:
            input: Coal
            pattern: 000 000 000
            tools: Crafting Table

    item: Block of Diamond
        recipe:
            input: Diamond
            pattern: 000 000 000
            tools: Crafting Table

    item: Block of Emerald
        recipe:
            input: Emerald
            pattern: 000 000 000
            tools: Crafting Table

    item: Block of Gold
        recipe:
            input: Gold Ingot
            pattern: 000 000 000
            tools: Crafting Table

    item: Block of Iron
        recipe:
            input: Iron Ingot
            pattern: 000 000 000
            tools: Crafting Table

    item: Block of Quartz
        recipe:
            input: Nether Quartz
            pattern: 00. 00. ...
        recipe:
            input: Nether Quartz Ore, Soul Sand
            pattern: ... 0.1 ...
            tools: Induction Smelter (Basic)

    item: Block of Redstone
        recipe:
            input: Redstone Ore, Sand
            pattern: ... 0.1 ...
            tools: Induction Smelter (Basic)
        recipe:
            input: Redstone
            pattern: 000 000 000
            tools: Crafting Table

    item: Charcoal
        recipe:
            input: Acacia Wood
            pattern: ... .0. ...
            tools: Redstone Furnace (Basic)
        recipe:
            input: Compressed Sawdust
            pattern: ... .0. ...
            tools: Redstone Furnace (Basic)
        recipe:
            input: Hay Bale
            pattern: ... .0. ...
            tools: Redstone Furnace (Basic)
        recipe:
            input: Oak Wood
            pattern: ... .0. ...
            tools: Redstone Furnace (Basic)
        recipe:
            input: Acacia Wood, Furnace Fuel
            pattern: .0. ... .1.
            tools: Furnace
        recipe:
            input: Compressed Sawdust, Furnace Fuel
            pattern: .0. ... .1.
            tools: Furnace
        recipe:
            input: Furnace Fuel, Oak Wood
            pattern: .1. ... .0.
            tools: Furnace

    item: Chiseled Quartz Block
        recipe:
            input: Quartz Slab
            pattern: 0.. 0.. ...

    item: Coal
        gatherable: yes
        recipe:
            input: Block of Coal
            pattern: 0.. ... ...
            quantity: 9
        recipe:
            input: Coal Ore
            pattern: ... .0. ...
            tools: Redstone Furnace (Basic)
        recipe:
            input: Coal Ore
            pattern: ... .0. ...
            quantity: 3
            tools: Pulverizer (Basic)
        recipe:
            input: Coal Ore, Furnace Fuel
            pattern: .0. ... .1.
            tools: Furnace

    item: Coal Ore
        gatherable: yes

    item: Diamond
        gatherable: yes
        recipe:
            input: Block of Diamond
            pattern: 0.. ... ...
            quantity: 9
        recipe:
            input: Diamond Axe
            pattern: ... .0. ...
            quantity: 3
            tools: Pulverizer (Basic)
        recipe:
            input: Diamond Boots
            pattern: ... .0. ...
            quantity: 4
            tools: Pulverizer (Basic)
        recipe:
            input: Diamond Chestplate
            pattern: ... .0. ...
            quantity: 8
            tools: Pulverizer (Basic)
        recipe:
            input: Diamond Fishing Rod
            pattern: ... .0. ...
            quantity: 2
            tools: Pulverizer (Basic)
        recipe:
            input: Diamond Helmet
            pattern: ... .0. ...
            quantity: 5
            tools: Pulverizer (Basic)
        recipe:
            input: Diamond Hoe
            pattern: ... .0. ...
            quantity: 2
            tools: Pulverizer (Basic)
        recipe:
            input: Diamond Horse Armor
            pattern: ... .0. ...
            quantity: 5
            tools: Pulverizer (Basic)
        recipe:
            input: Diamond Leggings
            pattern: ... .0. ...
            quantity: 7
            tools: Pulverizer (Basic)
        recipe:
            input: Diamond Ore
            pattern: ... .0. ...
            tools: Redstone Furnace (Basic)
        recipe:
            input: Diamond Ore
            pattern: ... .0. ...
            quantity: 2
            tools: Pulverizer (Basic)
        recipe:
            input: Diamond Pickaxe
            pattern: ... .0. ...
            quantity: 3
            tools: Pulverizer (Basic)
        recipe:
            input: Diamond Reinforced Bow
            pattern: ... .0. ...
            quantity: 2
            tools: Pulverizer (Basic)
        recipe:
            input: Diamond Shears
            pattern: ... .0. ...
            quantity: 2
            tools: Pulverizer (Basic)
        recipe:
            input: Diamond Shovel
            pattern: ... .0. ...
            tools: Pulverizer (Basic)
        recipe:
            input: Diamond Sickle
            pattern: ... .0. ...
            quantity: 3
            tools: Pulverizer (Basic)
        recipe:
            input: Diamond Sword
            pattern: ... .0. ...
            quantity: 2
            tools: Pulverizer (Basic)
        recipe:
            input: Diamond Ore, Furnace Fuel
            pattern: .0. ... .1.
            tools: Furnace
        recipe:
            input: Diamond Nugget
            pattern: 000 000 000
            tools: Crafting Table

    item: Diamond Ore
        gatherable: yes

    item: Emerald
        gatherable: yes
        recipe:
            input: Block of Emerald
            pattern: 0.. ... ...
            quantity: 9
        recipe:
            input: Emerald Ore
            pattern: ... .0. ...
            tools: Redstone Furnace (Basic)
        recipe:
            input: Emerald Ore
            pattern: ... .0. ...
            quantity: 2
            tools: Pulverizer (Basic)
        recipe:
            input: Emerald Ore, Furnace Fuel
            pattern: .0. ... .1.
            tools: Furnace
        recipe:
            input: Emerald Nugget
            pattern: 000 000 000
            tools: Crafting Table

    item: Emerald Ore
        gatherable: yes

    item: Flint
        gatherable: yes
        recipe:
            input: Gravel
            pattern: ... .0. ...
            tools: Pulverizer (Basic)

    item: Glowstone
        recipe:
            input: Glowstone Dust
            pattern: 00. 00. ...

    item: Glowstone Dust
        gatherable: yes
        recipe:
            input: Glowstone
            pattern: ... .0. ...
            quantity: 4
            tools: Pulverizer (Basic)
        recipe:
            input: Redstone Lamp
            pattern: ... .0. ...
            quantity: 4
            tools: Pulverizer (Basic)
        recipe:
            input: Nitor Wart Spores, Phyto-Gro
            pattern: ... 0.1 ...
            tools: Phytogenic Insolator (Basic)
        recipe:
            input: Nitor Wart Spores, Rich Phyto-Gro
            pattern: ... 0.1 ...
            quantity: 3
            tools: Phytogenic Insolator (Basic)

    item: Gold Ingot
        gatherable: yes
        recipe:
            input: Block of Gold
            pattern: 0.. ... ...
            quantity: 9
        recipe:
            ignoreDuringCrafting: yes
            input: Gold Ore, Pyrotheum Dust
            pattern: ... 10. ...
        recipe:
            input: Gold Ore
            pattern: ... .0. ...
            tools: Redstone Furnace (Basic)
        recipe:
            input: Pulverized Gold
            pattern: ... .0. ...
            tools: Redstone Furnace (Basic)
        recipe:
            input: Cinnabar, Gold Ore
            pattern: ... 1.0 ...
            quantity: 3
            tools: Induction Smelter (Basic)
        recipe:
            input: Clock, Sand
            pattern: ... 1.0 ...
            quantity: 4
            tools: Induction Smelter (Basic)
        recipe:
            input: Furnace Fuel, Gold Ore
            pattern: .1. ... .0.
            tools: Furnace
        recipe:
            input: Furnace Fuel, Pulverized Gold
            pattern: .1. ... .0.
            tools: Furnace
        recipe:
            input: Gold Fishing Rod, Sand
            pattern: ... 1.0 ...
            quantity: 2
            tools: Induction Smelter (Basic)
        recipe:
            input: Gold Ore, Pyrotheum Dust
            pattern: ... 0.1 ...
            quantity: 2
            tools: Induction Smelter (Basic)
        recipe:
            input: Gold Ore, Rich Slag
            pattern: ... 0.1 ...
            quantity: 3
            tools: Induction Smelter (Basic)
        recipe:
            input: Gold Ore, Sand
            pattern: ... 0.1 ...
            quantity: 2
            tools: Induction Smelter (Basic)
        recipe:
            input: Gold Reinforced Bow, Sand
            pattern: ... 1.0 ...
            quantity: 2
            tools: Induction Smelter (Basic)
        recipe:
            input: Gold Shears, Sand
            pattern: ... 1.0 ...
            quantity: 2
            tools: Induction Smelter (Basic)
        recipe:
            input: Gold Sickle, Sand
            pattern: ... 1.0 ...
            quantity: 3
            tools: Induction Smelter (Basic)
        recipe:
            input: Golden Axe, Sand
            pattern: ... 1.0 ...
            quantity: 3
            tools: Induction Smelter (Basic)
        recipe:
            input: Golden Boots, Sand
            pattern: ... 1.0 ...
            quantity: 4
            tools: Induction Smelter (Basic)
        recipe:
            input: Golden Chestplate, Sand
            pattern: ... 1.0 ...
            quantity: 8
            tools: Induction Smelter (Basic)
        recipe:
            input: Golden Helmet, Sand
            pattern: ... 1.0 ...
            quantity: 5
            tools: Induction Smelter (Basic)
        recipe:
            input: Golden Hoe, Sand
            pattern: ... 1.0 ...
            quantity: 2
            tools: Induction Smelter (Basic)
        recipe:
            input: Golden Leggings, Sand
            pattern: ... 1.0 ...
            quantity: 7
            tools: Induction Smelter (Basic)
        recipe:
            input: Golden Pickaxe, Sand
            pattern: ... 1.0 ...
            quantity: 3
            tools: Induction Smelter (Basic)
        recipe:
            input: Golden Shovel, Sand
            pattern: ... 1.0 ...
            tools: Induction Smelter (Basic)
        recipe:
            input: Golden Sword, Sand
            pattern: ... 1.0 ...
            quantity: 2
            tools: Induction Smelter (Basic)
        recipe:
            input: Sand, Weighted Pressure Plate (Light)
            pattern: ... 0.1 ...
            quantity: 2
            tools: Induction Smelter (Basic)
        recipe:
            input: 2 Pulverized Gold, Sand
            pattern: ... 0.1 ...
            quantity: 2
            tools: Induction Smelter (Basic)
        recipe:
            input: Gold Nugget
            pattern: 000 000 000
            tools: Crafting Table

    item: Gold Nugget
        recipe:
            input: Gold Ingot
            pattern: 0.. ... ...
            quantity: 9
        recipe:
            input: Aurigold Seeds, Phyto-Gro
            pattern: ... 0.1 ...
            tools: Phytogenic Insolator (Basic)
        recipe:
            input: Aurigold Seeds, Rich Phyto-Gro
            pattern: ... 0.1 ...
            quantity: 3
            tools: Phytogenic Insolator (Basic)

    item: Gold Ore
        gatherable: yes

    item: Grass Block
        gatherable: yes

    item: Ice
        recipe:
            input: 1000 Water
            pattern: ... .0. ...
            tools: Glacial Precipitator (Basic)

    item: Iron Ingot
        gatherable: yes
        recipe:
            input: Block of Iron
            pattern: 0.. ... ...
            quantity: 9
        recipe:
            ignoreDuringCrafting: yes
            input: Iron Ore, Pyrotheum Dust
            pattern: ... 10. ...
        recipe:
            input: Iron Ore
            pattern: ... .0. ...
            tools: Redstone Furnace (Basic)
        recipe:
            input: Pulverized Iron
            pattern: ... .0. ...
            tools: Redstone Furnace (Basic)
        recipe:
            input: Anvil, Sand
            pattern: ... 1.0 ...
            quantity: 31
            tools: Induction Smelter (Basic)
        recipe:
            input: Bucket, Sand
            pattern: ... 1.0 ...
            quantity: 3
            tools: Induction Smelter (Basic)
        recipe:
            input: Cauldron, Sand
            pattern: ... 1.0 ...
            quantity: 7
            tools: Induction Smelter (Basic)
        recipe:
            input: Cinnabar, Iron Ore
            pattern: ... 1.0 ...
            quantity: 3
            tools: Induction Smelter (Basic)
        recipe:
            input: Compass, Sand
            pattern: ... 1.0 ...
            quantity: 4
            tools: Induction Smelter (Basic)
        recipe:
            input: Flint and Steel, Sand
            pattern: ... 1.0 ...
            tools: Induction Smelter (Basic)
        recipe:
            input: Furnace Fuel, Iron Ore
            pattern: .1. ... .0.
            tools: Furnace
        recipe:
            input: Furnace Fuel, Pulverized Iron
            pattern: .1. ... .0.
            tools: Furnace
        recipe:
            input: Hopper, Sand
            pattern: ... 1.0 ...
            quantity: 5
            tools: Induction Smelter (Basic)
        recipe:
            input: Iron Axe, Sand
            pattern: ... 1.0 ...
            quantity: 3
            tools: Induction Smelter (Basic)
        recipe:
            input: Iron Boots, Sand
            pattern: ... 1.0 ...
            quantity: 4
            tools: Induction Smelter (Basic)
        recipe:
            input: Iron Chestplate, Sand
            pattern: ... 1.0 ...
            quantity: 8
            tools: Induction Smelter (Basic)
        recipe:
            input: Iron Door, Sand
            pattern: ... 1.0 ...
            quantity: 6
            tools: Induction Smelter (Basic)
        recipe:
            input: Iron Fishing Rod, Sand
            pattern: ... 1.0 ...
            quantity: 2
            tools: Induction Smelter (Basic)
        recipe:
            input: Iron Helmet, Sand
            pattern: ... 1.0 ...
            quantity: 5
            tools: Induction Smelter (Basic)
        recipe:
            input: Iron Hoe, Sand
            pattern: ... 1.0 ...
            quantity: 2
            tools: Induction Smelter (Basic)
        recipe:
            input: Iron Leggings, Sand
            pattern: ... 1.0 ...
            quantity: 7
            tools: Induction Smelter (Basic)
        recipe:
            input: Iron Ore, Pyrotheum Dust
            pattern: ... 0.1 ...
            quantity: 2
            tools: Induction Smelter (Basic)
        recipe:
            input: Iron Ore, Rich Slag
            pattern: ... 0.1 ...
            quantity: 3
            tools: Induction Smelter (Basic)
        recipe:
            input: Iron Ore, Sand
            pattern: ... 0.1 ...
            quantity: 2
            tools: Induction Smelter (Basic)
        recipe:
            input: Iron Pickaxe, Sand
            pattern: ... 1.0 ...
            quantity: 3
            tools: Induction Smelter (Basic)
        recipe:
            input: Iron Reinforced Bow, Sand
            pattern: ... 1.0 ...
            quantity: 2
            tools: Induction Smelter (Basic)
        recipe:
            input: Iron Shovel, Sand
            pattern: ... 1.0 ...
            tools: Induction Smelter (Basic)
        recipe:
            input: Iron Sickle, Sand
            pattern: ... 1.0 ...
            quantity: 3
            tools: Induction Smelter (Basic)
        recipe:
            input: Iron Sword, Sand
            pattern: ... 1.0 ...
            quantity: 2
            tools: Induction Smelter (Basic)
        recipe:
            input: Sand, Shears
            pattern: ... 0.1 ...
            quantity: 2
            tools: Induction Smelter (Basic)
        recipe:
            input: Sand, Slightly Damaged Anvil
            pattern: ... 0.1 ...
            quantity: 22
            tools: Induction Smelter (Basic)
        recipe:
            input: Sand, Very Damaged Anvil
            pattern: ... 0.1 ...
            quantity: 13
            tools: Induction Smelter (Basic)
        recipe:
            input: Sand, Weighted Pressure Plate (Heavy)
            pattern: ... 0.1 ...
            quantity: 2
            tools: Induction Smelter (Basic)
        recipe:
            input: 2 Pulverized Iron, Sand
            pattern: ... 0.1 ...
            quantity: 2
            tools: Induction Smelter (Basic)
        recipe:
            input: 8 Iron Bars, Sand
            pattern: ... 1.0 ...
            quantity: 3
            tools: Induction Smelter (Basic)
        recipe:
            input: Iron Nugget
            pattern: 000 000 000
            tools: Crafting Table

    item: Iron Ore
        gatherable: yes

    item: Lapis Lazuli Block
        recipe:
            input: Lapis Lazuli
            pattern: 000 000 000
            tools: Crafting Table

    item: Lapis Lazuli Ore
        gatherable: yes

    item: Nether Quartz
        gatherable: yes
        recipe:
            input: Block of Quartz
            pattern: ... .0. ...
            quantity: 4
            tools: Pulverizer (Basic)
        recipe:
            input: Chiseled Quartz Block
            pattern: ... .0. ...
            quantity: 4
            tools: Pulverizer (Basic)
        recipe:
            input: Nether Quartz Ore
            pattern: ... .0. ...
            tools: Redstone Furnace (Basic)
        recipe:
            input: Nether Quartz Ore
            pattern: ... .0. ...
            quantity: 3
            tools: Pulverizer (Basic)
        recipe:
            input: Pillar Quartz Block
            pattern: ... .0. ...
            quantity: 4
            tools: Pulverizer (Basic)
        recipe:
            input: Quartz Slab
            pattern: ... .0. ...
            quantity: 2
            tools: Pulverizer (Basic)
        recipe:
            input: Quartz Stairs
            pattern: ... .0. ...
            quantity: 6
            tools: Pulverizer (Basic)
        recipe:
            input: Furnace Fuel, Nether Quartz Ore
            pattern: .1. ... .0.
            tools: Furnace
        recipe:
            input: Quartz Shard
            pattern: 000 000 000
            tools: Crafting Table

    item: Nether Quartz Ore
        gatherable: yes

    item: Note Block
        recipe:
            input: Oak Wood Planks, Redstone
            pattern: 000 010 000
            tools: Crafting Table

    item: Packed Ice
        gatherable: yes
        recipe:
            input: 250 Gelid Cryotheum, Ice
            pattern: ... 1.0 ...
            tools: Fluid Transposer (Basic)

    item: Pillar Quartz Block
        recipe:
            input: Block of Quartz
            pattern: 0.. 0.. ...
            quantity: 2

    item: Redstone
        gatherable: yes
        recipe:
            input: Block of Redstone
            pattern: 0.. ... ...
            quantity: 9
        recipe:
            input: Hardened Energy Cell
            pattern: ... .0. ...
            quantity: 8
            tools: Pulverizer (Basic)
        recipe:
            input: Hardened Energy Cell Frame
            pattern: ... .0. ...
            quantity: 8
            tools: Pulverizer (Basic)
        recipe:
            input: Hardened Fluxduct
            pattern: ... .0. ...
            quantity: 2
            tools: Pulverizer (Basic)
        recipe:
            input: Leadstone Energy Cell
            pattern: ... .0. ...
            quantity: 8
            tools: Pulverizer (Basic)
        recipe:
            input: Leadstone Energy Cell Frame
            pattern: ... .0. ...
            quantity: 8
            tools: Pulverizer (Basic)
        recipe:
            input: Leadstone Fluxduct
            pattern: ... .0. ...
            tools: Pulverizer (Basic)
        recipe:
            input: Redstone Ore
            pattern: ... .0. ...
            quantity: 4
            tools: Redstone Furnace (Basic)
        recipe:
            input: Redstone Ore
            pattern: ... .0. ...
            quantity: 6
            tools: Pulverizer (Basic)
        recipe:
            input: Redstone Torch
            pattern: ... .0. ...
            tools: Sawmill (Basic)
        recipe:
            input: Furnace Fuel, Redstone Ore
            pattern: .1. ... .0.
            tools: Furnace
        recipe:
            input: Phyto-Gro, Redstodendron Seeds
            pattern: ... 1.0 ...
            tools: Phytogenic Insolator (Basic)
        recipe:
            input: Redstodendron Seeds, Rich Phyto-Gro
            pattern: ... 0.1 ...
            quantity: 3
            tools: Phytogenic Insolator (Basic)

    item: Redstone Ore
        gatherable: yes

    item: Snow (block)
        recipe:
            input: Snowball
            pattern: 00. 00. ...
        recipe:
            input: 500 Water
            pattern: ... .0. ...
            tools: Glacial Precipitator (Basic)

    item: Snow (layer)
        recipe:
            input: Snow (block)
            pattern: 000 ... ...
            quantity: 6
            tools: Crafting Table

    item: Snowball
        gatherable: yes
        recipe:
            input: 250 Water
            pattern: ... .0. ...
            quantity: 4
            tools: Glacial Precipitator (Basic)

group: Mob Drops (animals)

    item: Black Wool
        recipe:
            input: Ink Sac, Wool
            pattern: ... 10. ...

    item: Blue Wool
        recipe:
            input: Lapis Lazuli, Wool
            pattern: ... 10. ...

    item: Brown Wool
        recipe:
            input: Cocoa Beans, Wool
            pattern: ... 10. ...

    item: Cyan Wool
        recipe:
            input: Cyan Dye, Wool
            pattern: ... 10. ...

    item: Egg
        gatherable: yes

    item: Feather
        gatherable: yes

    item: Gray Wool
        recipe:
            input: Gray Dye, Wool
            pattern: ... 10. ...

    item: Green Wool
        recipe:
            input: Cactus Green, Wool
            pattern: ... 10. ...

    item: Leather
        gatherable: yes
        recipe:
            input: Item Frame
            pattern: ... .0. ...
            tools: Sawmill (Basic)
        recipe:
            input: Leather Boots
            pattern: ... .0. ...
            quantity: 3
            tools: Sawmill (Basic)
        recipe:
            input: Leather Cap
            pattern: ... .0. ...
            quantity: 3
            tools: Sawmill (Basic)
        recipe:
            input: Leather Pants
            pattern: ... .0. ...
            quantity: 5
            tools: Sawmill (Basic)
        recipe:
            input: Leather Tunic
            pattern: ... .0. ...
            quantity: 6
            tools: Sawmill (Basic)

    item: Light Blue Wool
        recipe:
            input: Light Blue Dye, Wool
            pattern: ... 10. ...

    item: Light Gray Wool
        recipe:
            input: Light Gray Dye, Wool
            pattern: ... 10. ...

    item: Lime Wool
        recipe:
            input: Lime Dye, Wool
            pattern: ... 10. ...

    item: Magenta Wool
        recipe:
            input: Magenta Dye, Wool
            pattern: ... 10. ...

    item: Orange Wool
        recipe:
            input: Orange Dye, Wool
            pattern: ... 10. ...

    item: Pink Wool
        recipe:
            input: Pink Dye, Wool
            pattern: ... 10. ...

    item: Purple Wool
        recipe:
            input: Purple Dye, Wool
            pattern: ... 10. ...

    item: Red Wool
        recipe:
            input: Rose Red, Wool
            pattern: ... 10. ...

    item: Wool
        gatherable: yes
        recipe:
            input: Bone Meal, Wool
            pattern: ... 10. ...
        recipe:
            input: String
            pattern: 00. 00. ...
        recipe:
            input: Painting
            pattern: ... .0. ...
            tools: Sawmill (Basic)

    item: Yellow Wool
        recipe:
            input: Dandelion Yellow, Wool
            pattern: ... 10. ...

group: Mob Drops (monsters)

    item: Blaze Powder
        recipe:
            input: Blaze Rod
            pattern: ... .0. ...
            quantity: 2
        recipe:
            input: Blaze Rod
            pattern: ... .0. ...
            quantity: 4
            tools: Pulverizer (Basic)
        recipe:
            input: 200 Destabilized Redstone, Glowstone Dust
            pattern: ... 1.0 ...
            tools: Fluid Transposer (Basic)

    item: Blaze Rod
        gatherable: yes

    item: Bone
        gatherable: yes

    item: Creeper Head
        gatherable: yes

    item: Dragon Egg
        gatherable: yes

    item: Ender Pearl
        gatherable: yes

    item: Eye of Ender
        recipe:
            input: Blaze Powder, Ender Pearl
            pattern: ... 01. ...

    item: Head
        gatherable: yes

    item: Nether Star
        gatherable: yes

    item: Rotten Flesh
        gatherable: yes

    item: Skeleton Skull
        gatherable: yes

    item: Slimeball
        gatherable: yes

    item: Spider Eye
        gatherable: yes

    item: String
        gatherable: yes
        recipe:
            input: Black Wool
            pattern: ... .0. ...
            quantity: 4
            tools: Pulverizer (Basic)
        recipe:
            input: Blue Wool
            pattern: ... .0. ...
            quantity: 4
            tools: Pulverizer (Basic)
        recipe:
            input: Brown Wool
            pattern: ... .0. ...
            quantity: 4
            tools: Pulverizer (Basic)
        recipe:
            input: Cyan Wool
            pattern: ... .0. ...
            quantity: 4
            tools: Pulverizer (Basic)
        recipe:
            input: Gray Wool
            pattern: ... .0. ...
            quantity: 4
            tools: Pulverizer (Basic)
        recipe:
            input: Green Wool
            pattern: ... .0. ...
            quantity: 4
            tools: Pulverizer (Basic)
        recipe:
            input: Light Blue Wool
            pattern: ... .0. ...
            quantity: 4
            tools: Pulverizer (Basic)
        recipe:
            input: Light Gray Wool
            pattern: ... .0. ...
            quantity: 4
            tools: Pulverizer (Basic)
        recipe:
            input: Lime Wool
            pattern: ... .0. ...
            quantity: 4
            tools: Pulverizer (Basic)
        recipe:
            input: Magenta Wool
            pattern: ... .0. ...
            quantity: 4
            tools: Pulverizer (Basic)
        recipe:
            input: Orange Wool
            pattern: ... .0. ...
            quantity: 4
            tools: Pulverizer (Basic)
        recipe:
            input: Pink Wool
            pattern: ... .0. ...
            quantity: 4
            tools: Pulverizer (Basic)
        recipe:
            input: Purple Wool
            pattern: ... .0. ...
            quantity: 4
            tools: Pulverizer (Basic)
        recipe:
            input: Red Wool
            pattern: ... .0. ...
            quantity: 4
            tools: Pulverizer (Basic)
        recipe:
            input: Wool
            pattern: ... .0. ...
            quantity: 4
            tools: Pulverizer (Basic)
        recipe:
            input: Yellow Wool
            pattern: ... .0. ...
            quantity: 4
            tools: Pulverizer (Basic)

    item: Wither Skeleton Skull
        gatherable: yes

    item: Zombie Head
        gatherable: yes

group: Plants

    item: Cactus
        gatherable: yes
        recipe:
            input: Cactus, Phyto-Gro
            pattern: ... 0.1 ...
            quantity: 2
            tools: Phytogenic Insolator (Basic)
        recipe:
            input: Cactus, Rich Phyto-Gro
            pattern: ... 0.1 ...
            quantity: 6
            tools: Phytogenic Insolator (Basic)

    item: Dead Bush
        gatherable: yes

    item: Double Tallgrass
        gatherable: yes

    item: Fern
        gatherable: yes

    item: Grass
        gatherable: yes

    item: Large Fern
        gatherable: yes

    item: Lily Pad
        gatherable: yes
        recipe:
            input: Lily Pad, Phyto-Gro
            pattern: ... 0.1 ...
            quantity: 2
            tools: Phytogenic Insolator (Basic)
        recipe:
            input: Lily Pad, Rich Phyto-Gro
            pattern: ... 0.1 ...
            quantity: 6
            tools: Phytogenic Insolator (Basic)

    item: Mushroom (brown block)
        gatherable: yes

    item: Mushroom (red block)
        gatherable: yes

    item: Vines
        gatherable: yes
        recipe:
            input: Phyto-Gro, Vines
            pattern: ... 1.0 ...
            quantity: 2
            tools: Phytogenic Insolator (Basic)
        recipe:
            input: Rich Phyto-Gro, Vines
            pattern: ... 1.0 ...
            quantity: 6
            tools: Phytogenic Insolator (Basic)

group: Tools

    item: Carrot on a Stick
        recipe:
            input: Carrot, Fishing Rod
            pattern: 1.. .0. ...

    item: Clock
        recipe:
            input: Gold Ingot, Redstone
            pattern: .0. 010 .0.
            tools: Crafting Table

    item: Compass
        recipe:
            input: Iron Ingot, Redstone
            pattern: .0. 010 .0.
            tools: Crafting Table

    item: Diamond Axe
        recipe:
            input: Diamond, Stick
            pattern: 00. 01. .1.
            tools: Crafting Table

    item: Diamond Hoe
        recipe:
            input: Diamond, Stick
            pattern: 00. .1. .1.
            tools: Crafting Table

    item: Diamond Pickaxe
        recipe:
            input: Diamond, Stick
            pattern: 000 .1. .1.
            tools: Crafting Table

    item: Diamond Shovel
        recipe:
            input: Diamond, Stick
            pattern: 0.. 1.. 1..
            tools: Crafting Table

    item: Empty Map
        recipe:
            input: Compass, Paper
            pattern: 111 101 111
            tools: Crafting Table
        recipe:
            input: Map, Paper
            pattern: 111 101 111
            tools: Crafting Table

    item: Fishing Rod
        recipe:
            input: Stick, String
            pattern: ..0 .01 0.1
            tools: Crafting Table

    item: Flint and Steel
        recipe:
            input: Flint, Iron Ingot
            pattern: ... 01. ...

    item: Golden Axe
        recipe:
            input: Gold Ingot, Stick
            pattern: 00. 01. .1.
            tools: Crafting Table

    item: Golden Hoe
        recipe:
            input: Gold Ingot, Stick
            pattern: 00. .1. .1.
            tools: Crafting Table

    item: Golden Pickaxe
        recipe:
            input: Gold Ingot, Stick
            pattern: 000 .1. .1.
            tools: Crafting Table

    item: Golden Shovel
        recipe:
            input: Gold Ingot, Stick
            pattern: 0.. 1.. 1..
            tools: Crafting Table

    item: Iron Axe
        recipe:
            input: Iron Ingot, Stick
            pattern: 00. 01. .1.
            tools: Crafting Table

    item: Iron Hoe
        recipe:
            input: Iron Ingot, Stick
            pattern: 00. .1. .1.
            tools: Crafting Table

    item: Iron Pickaxe
        recipe:
            input: Iron Ingot, Stick
            pattern: 000 .1. .1.
            tools: Crafting Table

    item: Iron Shovel
        recipe:
            input: Iron Ingot, Stick
            pattern: 0.. 1.. 1..
            tools: Crafting Table

    item: Lead
        recipe:
            input: Slimeball, String
            pattern: 11. 10. ..1
            quantity: 2
            tools: Crafting Table

    item: Map
        gatherable: yes

    item: Name Tag
        gatherable: yes

    item: Saddle
        gatherable: yes

    item: Shears
        recipe:
            input: Iron Ingot
            pattern: .0. 0.. ...

    item: Stone Axe
        recipe:
            input: Cobblestone, Stick
            pattern: 00. 01. .1.
            tools: Crafting Table

    item: Stone Hoe
        recipe:
            input: Cobblestone, Stick
            pattern: 00. .1. .1.
            tools: Crafting Table

    item: Stone Pickaxe
        recipe:
            input: Cobblestone, Stick
            pattern: 000 .1. .1.
            tools: Crafting Table

    item: Stone Shovel
        recipe:
            input: Cobblestone, Stick
            pattern: 0.. 1.. 1..
            tools: Crafting Table

    item: TNT
        recipe:
            input: Gunpowder, Sand
            pattern: 010 101 010
            tools: Crafting Table

    item: Torch
        recipe:
            input: Charcoal, Stick
            pattern: 0.. 1.. ...
            quantity: 4
        recipe:
            input: Coal, Stick
            pattern: 0.. 1.. ...
            quantity: 4

    item: Wooden Axe
        recipe:
            input: Oak Wood Planks, Stick
            pattern: 00. 01. .1.
            tools: Crafting Table

    item: Wooden Hoe
        recipe:
            input: Oak Wood Planks, Stick
            pattern: 00. .1. .1.
            tools: Crafting Table

    item: Wooden Pickaxe
        recipe:
            input: Oak Wood Planks, Stick
            pattern: 000 .1. .1.
            tools: Crafting Table

    item: Wooden Shovel
        recipe:
            input: Oak Wood Planks, Stick
            pattern: 0.. 1.. 1..
            tools: Crafting Table

group: Transportation

    item: Activator Rail
        recipe:
            input: Iron Ingot, Redstone Torch, Stick
            pattern: 020 010 020
            quantity: 6
            tools: Crafting Table

    item: Boat
        recipe:
            input: Oak Wood Planks
            pattern: 0.0 000 ...
            tools: Crafting Table

    item: Detector Rail
        recipe:
            input: Iron Ingot, Pressure Plate (stone), Redstone
            pattern: 0.0 010 020
            quantity: 6
            tools: Crafting Table

    item: Minecart
        recipe:
            input: Iron Ingot
            pattern: 0.0 000 ...
            tools: Crafting Table

    item: Minecart with Chest
        recipe:
            input: Chest, Minecart
            pattern: 0.. 1.. ...

    item: Minecart with Command Block
        gatherable: yes

    item: Minecart with Furnace
        recipe:
            input: Furnace, Minecart
            pattern: 0.. 1.. ...

    item: Minecart with Hopper
        recipe:
            input: Hopper, Minecart
            pattern: 0.. 1.. ...

    item: Minecart with TNT
        recipe:
            input: Minecart, TNT
            pattern: 1.. 0.. ...

    item: Powered Rail
        recipe:
            input: Gold Ingot, Redstone, Stick
            pattern: 0.0 020 010
            quantity: 6
            tools: Crafting Table

    item: Rail
        recipe:
            input: Iron Ingot, Stick
            pattern: 0.0 010 0.0
            quantity: 16
            tools: Crafting Table

group: Trees

    item: Acacia Leaves
        gatherable: yes

    item: Acacia Sapling
        gatherable: yes

    item: Acacia Wood
        gatherable: yes

    item: Birch Leaves
        gatherable: yes

    item: Birch Sapling
        gatherable: yes

    item: Birch Wood
        gatherable: yes

    item: Dark Oak Leaves
        gatherable: yes

    item: Dark Oak Sapling
        gatherable: yes

    item: Dark Oak Wood
        gatherable: yes

    item: Jungle Leaves
        gatherable: yes

    item: Jungle Sapling
        gatherable: yes

    item: Jungle Wood
        gatherable: yes

    item: Oak Leaves
        gatherable: yes

    item: Oak Sapling
        gatherable: yes

    item: Oak Wood
        gatherable: yes

    item: Spruce Leaves
        gatherable: yes

    item: Spruce Sapling
        gatherable: yes

    item: Spruce Wood
        gatherable: yes

    item: Stick
        recipe:
            input: Crop Sticks
            pattern: ... .0. ...
        recipe:
            input: Oak Wood Planks
            pattern: 0.. 0.. ...
            quantity: 4

group: Weapons

    item: Arrow
        recipe:
            input: Feather, Flint, Stick
            pattern: 1.. 2.. 0..
            quantity: 4
            tools: Crafting Table

    item: Bow
        recipe:
            input: Stick, String
            pattern: .01 0.1 .01
            tools: Crafting Table

    item: Diamond Sword
        recipe:
            input: Diamond, Stick
            pattern: 0.. 0.. 1..
            tools: Crafting Table

    item: Golden Sword
        recipe:
            input: Gold Ingot, Stick
            pattern: 0.. 0.. 1..
            tools: Crafting Table

    item: Iron Sword
        recipe:
            input: Iron Ingot, Stick
            pattern: 0.. 0.. 1..
            tools: Crafting Table

    item: Stone Sword
        recipe:
            input: Cobblestone, Stick
            pattern: 0.. 0.. 1..
            tools: Crafting Table

    item: Wooden Sword
        recipe:
            input: Oak Wood Planks, Stick
            pattern: 0.. 0.. 1..
            tools: Crafting Table

