schema: 1

description: <<-END
High Speed Track, or H.S. Track (as specified in the hot bar and inventory) is used mainly for fast travel over a straight distance. They are the base of a High Speed line. This track is used typically on main lines. Turns are not advised when using these tracks, but it is simple enough to add turns. Just as normal rails, booster tracks, when not powered, will slow down the minecart or whatever vehicle your using.
(Images are coming, expect them by November 30th, sorry for the inconvenience!)
The way you make a turn using H.S. Track is by first slowing down the minecart with a unpowered H.S. Booster Track or a H.S. transition track. See [[H.S. Booster Track]] for information on them, or [[H.S. Transition Track]] for information on H.S. Transition tracks. You then add a 10-15 block space of no boosters. Once you have that done, you can then add the turn, which is the same as a normal rail/track. Be cautious though, for if your traveling when you take a turn, it could be disastrous. The result is death to the player, and a medium explosion around. The explosion can be powerful enough to destroy ore(s). If you created a successful and safe turn, you will go around the turn without crashing. Just like normal rails/tracks, H.S. tracks will also go downhill and uphill. 
END


