schema: 1

name:             Modular PowerSuits
author:           MachineMuse
description:      An expandable suit of powered armor while nearly infinite expansions, options, and customizations.
homePageUrl:      http://machinemuse.net/
documentationUrl: http://machinemuse.net/recipes.php
downloadUrl:      http://machinemuse.net/download.php

version: 0.11.0-300-thermal-expansion
version: 0.11.0-300-vanilla
