schema: 1

description: Bone Meal is used both as white dye and to fertilize growing plants. Fertilizing is done by right-clicking the plant with the bone meal.  Nearly any plant in the game from [[Wheat]] and [[Carrot]]s all the way up to [[Jungle Sapling]]s can be fertilized. Each time some is used, green particles will emanate from the plant, and it will advance somewhat toward maturity (though often not all the way).


