schema: 1

description: The Tier 2 Dungeon Key is dropped by the boss of the Mars dungeon.  In order to open the [[Treasure Chest (Tier 2)]], you'll need to right-click it with the key.  Since each dungeon is randomly generated, it's possible you may encounter the treasure chest *before* you encounter the boss.  If this happens, keep searching until you find it.  In rare cases, a dungeon can sometimes generate without a boss at all.  In that case, you won't be able to open the chest.


