schema: 1

name:             Tinker's Construct
author:           mDiyo, boni
description:      Learn low-tech metal smelting to create customizable tools and weapons to compliment an equally customizable set of armor.
homePageUrl:      http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1287648-tinkers-construct

version: 1.7.10-1.8.8

video: KDwE3OHVjDc, Basics
video: B8_jJy12eZo, Smelting
video: Lx-WiRDH1mg, Everything Else
