schema: 1

description: The Basic Gate is a crafting component for most, if not all other gates in Buildcraft. It has one "if" statement it can use, and it can only use Red Pipe Wire, and redstone signals, as well as several cool things with many inventories / tanks to do its job. NOTE: This item is crafted inside the Assembly Table, which requires lasers to receive RF energy, as it does NOT get RF on its own.


