schema: 1

description: The Soul Fragment is a small bit of your soul carved off and made into an item.  To get one, place an [[Etheric Sword]] in your inventory's 2x2 crafting grid.  The output will be a soul fragment.  Beware, though!  If you take it, you'll permanently lose one heart from your maximum health!  If you change your mind, you can right-click with the soul fragment in hand to return your health to normal.


