schema: 1

description: <<-END
Copper Oreberry Bushes produce [[Concentrated Essence Berry]]s which can be be eated to given the player a little experience.

The berries can be picked when ripe by right-clicking the plant. The bush itself can be obtained by breaking it like any other block (no special tool is required). They can be planted on grass or dirt. When planted, they are tiny, immature bushes which require some time to become full-sized.
END


