schema: 1

description: The Thermal Padding Boots are one part of a thermal protection suit.  For a complete suit, you'll also need [[Thermal Padding Helm]], [[Thermal Padding Chestpiece]], and [[Thermal Padding Leggings]].  This equipment is only necessary in especially harsh and cold environments (e.g., Mars).  You equip it next to the regular oxygen suit on the Galacticraft inventory section.


