schema: 1

description: <<-END
The Unstable Ingot is exactly what it says: unstable.  Which is to say, if you create one, you have 10 seconds to use it or it will explode, doing immense damage to you, your crafting table, and everything around you.  Therefore, you must be quite sure you're ready with all your materials for your next recipe **BEFORE** you start crafting!

To create an Unstable Ingot without danger of explosions, first create 9 [[Semi-stable Nugget]]s and craft them into an ingot.  Such ingots have the benefit of not exploding, but at a cost: semi-stable nuggets are made with gold instead of iron.
END


