schema: 1

description: <<-END
A [[Basic Solar Panel]] is a device that can be placed to generate energy from the sun.

Unlike the [[Advanced Solar Panel]], the basic one does not adjust to the sun, and is therefore only collecting an ideal amount of energy when the sun is directly above.

It is multi-block device that consists of a base block, the pole, and a solar array that is 3x3 in size. When placed on flat land, solar arrays need at least 2 blocks between each other. 
END


