schema: 1

description: <<-END
Blaze Rods can be obtained by killing Blazes in the Nether. Blazes only spawn within Nether Fortresses, and are most easily found by locating a Blaze spawner.

![](blaze-spawner.png)

The primary use of Blaze Rods is to create a [[Brewing Stand]], and then to create [[Blaze Powder]] for use in making [[Magma Cream]]s for potions or in crafting an [[Eye of Ender]] from [[Ender Pearl]]s.
END


