schema: 1

name: BuildCraft
author: SpaceToad, BuildCraft Team
description: Extending Minecraft with pipes, auto-crafting, quarries, engines and much more!
homePageUrl: http://www.mod-buildcraft.com/

version: 7.1.18

video: vCtoPsfct0g, Transport Pipes
video: VKy-WoYRym4, Fluid Pipes
video: 4Z-4-49fsGk, Power
video: 1P4l8xHvLcI, Gates
video: GBlbL5i5Xt0, Mining Machines
video: kPcxPLsjlR4, Crafting Machines
video: Tbr69hhqtA8, Robots
