schema: 1

description: The Thermal Padding Chestpiece is one part of a thermal protection suit.  For a complete suit, you'll also need [[Thermal Padding Helm]], [[Thermal Padding Leggings]], and [[Thermal Padding Boots]].  This equipment is only necessary in especially harsh and cold environments (e.g., Mars).  You equip it next to the regular oxygen suit on the Galacticraft inventory section.


