schema: 1

description: High Speed Transition Track is used mainly for transitioning from different areas of track. They are mainly used in high speed-medium speed an medium speed- high speed track transitions, hence the name, H.S. Transition Track. When using this track, it is important to realize that when the track is powered, it will act as a booster, and accelerate the minecart or vehicle. These tracks are generally pared with [[H.S. Track]] in order to provide a smooth experience. [More coming soon!]


