schema: 1

description: <<-END
The Peaceful Table is a block added by Extra Utilities, that allows players who play on peaceful to get mob drops. In order for the table to work, it has to be placed in the world adjacent to a chest (or any block with an inventory) which has a sword in it. The table will occasionally spawn a mob and kill it instantly with the provided sword. The sword will take damage appropriate to the hits needed to kill the mob with the sword in the inventory. In other words, better swords last longer. Enchantments are also taken into account. Looting will give extra mob drops. Sharpness and Unbreaking will make the swords last longer.
A Peaceful Table may be placed in the Nether in order to get Nether mob drops; but must be placed in a Nether Fortress in order to get Blaze and Wither Skeleton drops. A Peaceful Table may be placed in the End in order to get Enderman drops.
Note that the table will not work if the difficulty is not set to Peaceful, and killed mobs make the respective death sounds when killed.
END


