schema: 1

description: <<-END
A chest is a block which can hold other items. A single chest placed by itself can hold 27 stacks. When two chests are placed
side-by-side, they merge into a double chest capable of holding 54 stacks.  When broken, a chest will drop all the items it
contains.  Because of this, it is impossible to move a chest with its items intact in vanilla Minecraft.  However, the [[Dolly]]
from JABBA is able to pick up a chest with all the items intact and place it back down again somewhere else.
END
