#!/bin/bash

MODULE=$(basename $PWD)
QUIET="NO"
while [[ "$1" != "" ]]; do
    case "$1" in
        "-q") QUIET="YES";;
    esac
    shift
done

CHANGES=$(git log --oneline origin/master..master | while read LINE; do echo "    $LINE"; done)

if [[ "$CHANGES" != "" ]]; then
    printf "\nUnpublished changes for $MODULE:\n$CHANGES\n\n"
elif [[ "$QUIET" == "NO" ]]; then
    printf "No unpublished changes for $MODULE\n\n"
fi
