schema: 1

description: <<-END
Can be used to move a [[Better Barrel]] while maintaining its inventory and upgrades. Useful if you are moving your early-game collection of random barrels to a well-organized, obsidian-plated room in the middle of your base.

The Dolly can also be used to transport similar storage items from other mods, such as a vannilla [[Chest]], an [[Iron Chest]] or that [[DirtChest 9000!]] that your friend put in front of your door to annoy you.
END


