schema: 1

description: The Metal Former is a machine which transforms raw metal ingots into a variety of useful shapes: wires, plates, cells, etc.  The majority of what it makes can also be made by hand using a combination of the [[Forge Hammer]] and [[Cutter]], but, unlike those tools, the Metal Former can be automated and doesn't wear out.  It's generally well worth the investment early on in your build as it will save you a lot of time.


