schema: 1

description: <<-END
Reinforced Tracks are stronger than Vanilla Minecraft [[Rail]]s and are used when the player wants a explosion resistant section of track. If an explosion were to happen (Creeper, [[TNT]], etc) the Reinforced Track would not break unlike other rails. It is also used when transitioning from [[H.S. Track]] to other types of track. Using Reinforced Track when doing that type of transition will prevent the chance of a large crash. Precautions must be taken though, when doing this.

See [[H.S. Track]] for precautions and how to make safe transitions and turns.
END


