schema: 1

description: <<-END
The RE-Battery is a small, portable, storage device for a small amount of IC2 power (10kEU).  In addition to being used as a crafting ingredient in many powered machines and tools, it can be used to re-charge your equipment on the fly.  Just select it in the hotbar, hold down the right mouse button, and it will slowly transfer energy to any electric tools in your inventory.

It can be charged in any device with a charging slot (e.g., a [[Generator]], [[BatBox]], [[CESU]], etc.)
END


